substitutions:
# Указываем название устройства
  name: kitchen-lighting
  last_name: boiler
  device_description: "Выключатель кухня"
 
# Указываем ID сенсоров в HA

  sensor_uv_index: sensor.iaroslavskaia_uv_index
  sensor_geomagnetic: sensor.iaroslavskaia_geomagnetic_field
  sensor_temperature: sensor.kitchen_t
  sensor_humidity: sensor.kitchen_humidity
  sensor_pressure: sensor.iaroslavskaia_pressure
  sensor_co2: sensor.holl_co2
  sensor_weather: weather.iaroslavskaia
  sensor_iaq: sensor.holl_iaq
  sensor_iaq_c: sensor.holl_iaq_classification
  sensor_voc: sensor.holl_voc
  sensor_lux: sensor.holl_p

# Icon page setting_page
  page_home: weather #_anime

  botton_icon0: "󱠝" #countertop_outline
  botton_page0: kitchen_page

  botton_icon1: "\U000F0FD0" #bed-queen
  botton_page1: holl_page


  botton_icon2: "\U000F0454" # remote
  botton_page2: lg_remoute

  background_boot: back6
  background_weather: back6
  background_kitchen: back6
  background_holl: back6
  background_lg: back6
  background_button4: back6
  background_button6: back6
  background_button8: back6
  background_button10: back6
  background_button12: back6
  background_button16: back6
  background_slider4v: back6
  background_slider4g: back6
  background_slider4b: back6

  lightbulb: "󰌵"
#-------------------------------------------
# ESPHOME PLATFORM SETTINGS
#-------------------------------------------
esphome:
  name: "${name}"
  comment: "${device_description}"
  platformio_options:

    board_build.flash_mode: dio
    build_flags: "-DBOARD_HAS_PSRAM"
    board_build.arduino.memory_type: qio_opi
    board_build.psram_type: opi
    board_upload.maximum_size: 16777216
    board_upload.maximum_ram_size: 524288

  on_boot:
    - light.turn_on: backlight
    - delay: 5s
    - lvgl.widget.hide: boot_screen
    - lvgl.slider.update:
        id: dimmer_slider
        value: !lambda return id(backlight).remote_values.get_brightness() * 100;

#-------------------------------------------
# ESP MCU SETTINGS for
# Guition ESP32-S3-4848S040
#-------------------------------------------
esp32:
  board: esp32-s3-devkitc-1
  variant: esp32s3
  flash_size: 16MB
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_ESP32S3_DEFAULT_CPU_FREQ_240: "y"
      CONFIG_ESP32S3_DATA_CACHE_64KB: "y"
      CONFIG_ESP32S3_DATA_CACHE_LINE_64B: "y"
      CONFIG_SPIRAM_FETCH_INSTRUCTIONS: y
      CONFIG_SPIRAM_RODATA: y
     # CONFIG_ESP32_S3_BOX_BOARD: "y"
    #components:
    #  - name: esp32_s3_box_3_board
    #    source: github://jesserockz/esp32-s3-box-3-board@main
     #   refresh: 0s
#-------------------------------------------
# Logger #32 356 байт
#-------------------------------------------
logger: 

i2c:
    sda: GPIO19
    scl: GPIO45

spi:
    clk_pin: GPIO48
    mosi_pin: GPIO47

#-------------------------------------------
# PSRAM
#-------------------------------------------
psram:
  mode: octal
  speed: 80MHz

# ----------------------------------------- #
# -------------- COLORS ------------------- #
# ----------------------------------------- #
color:
  - id: color_black
    hex: 0d0d0d
  - id: color_dark_gray
    hex: 333333
  - id: color_gray
    hex: 666666
  - id: color_white
    hex: f2f0eb
  - id: color_red
    hex: ff0000
  - id: color_crimson
    hex: f5075c
  - id: color_blue
    hex: 2fc0ff
  - id: color_yellow
    hex: e7c12c
  - id: color_amber
    hex: f4a900
  - id: color_mint
    hex: 39d19c
  - id: color_green
    hex: 00ff00
  - id: color_orange
    hex: f07c40
  - id: color_deep_orange
    hex: ff6600
  - id: color_violet
    hex: 9670d6
  - id: color_dark_blue
    hex: 4867aa


#-------------------------------------------
# Packages
#-------------------------------------------
packages:
  wifi: !include packages/wifi.yaml

# Раставить страницы в желаемой очередности, barometr можно использовать 1 вариант
 #weather: !include packages/weather_anime.yaml # выбрать один из двух weather #jpg:3 689 528 байт без 2 603 377 байт
  weather: !include packages/weather.yaml # выбрать один из двух weather

  #button4: !include packages/button-4.yaml
  #button6: !include packages/button-6.yaml
  #button8: !include packages/button-8.yaml
  #button10: !include packages/button-10.yaml
  #button12: !include packages/button-12.yaml
  #button16: !include packages/button-16.yaml
  #slider4v: !include packages/slider-4v.yaml
  #slider4g: !include packages/slider-4g.yaml
  #slider4b: !include packages/slider-4b.yaml
  kitchen: !include packages/kitchen_light.yaml # 30 844
  holl: !include packages/holl_light.yaml # 29 420
  #boiler: !include packages/boiler.yaml
  lg: !include packages/lg_light.yaml  #495 288
 # clock: !include packages/clock_page.yaml
  #barometr: !include packages/barometr_page.yaml # выбрать один из двух barometr
  barometr: !include packages/barometr_bme680_page.yaml  # выбрать один из двух barometr
  geomag: !include packages/geomag.yaml
 # UV: !include packages/UV_page.yaml
  #humm: !include packages/humm-page.yaml

#-------------------------------------------
# IMAGE
#-------------------------------------------
image:
 # - file: 'picture/ha_logo.png'
  #  id: boot_logo
  #  resize: 200x200
 #   type: RGB565
  #  use_transparency: true
  - file: 'picture/back6.png'
    id: back6
    type: RGB565
  #- file: 'picture/back7.png'
  #  id: back7
   # type: RGB565

#-------------------------------------------
# FONT
#-------------------------------------------
font:   
  - file: "gfonts://Roboto"
    id: roboto36
    glyphs: |-
      !"%()+=,-_.:³°₂μ0123456789АБВГДЕЁЖЗИЙКЛМНОПРСТУФХЦЧЩЬЫЪЭЮЯABCDEFGHIJKLMNOPQRSTUVWXYZ абвгдеёжзийклмнопрстуфхцчщьыъэюяabcdefghijklmnopqrstuvwxyz'
    # gfonts://family[@weight]
    size: 36
    bpp: 4     

  - file: "gfonts://Roboto"
    id: roboto24
    glyphs: |-
      !"%()+=,-_.:³°₂μ0123456789АБВГДЕЁЖЗИЙКЛМНОПРСТУФХЦЧШЩЬЫЪЭЮЯABCDEFGHIJKLMNOPQRSTUVWXYZ абвгдеёжзийклмнопрстуфхцчшщьыъэюяabcdefghijklmnopqrstuvwxyz'
    # gfonts://family[@weight]
    size: 24
    bpp: 4  

  - file: "font/DSEG7ModernMini-Bold.ttf"
    id: SEG36
    glyphs: |-
      :.-0123456789'
    size: 36

    bpp: 4  
  - file: "gfonts://Roboto"
    id: menu24
    size: 24
    bpp: 4
    extras:
      - file: 'font/materialdesignicons-webfont.ttf' # http://materialdesignicons.com/cdn/7.4.47/ 
        glyphs: [
          "\U000F06A1",
          "\U000F0141",
          "\U000F0142"
        ]

#-------------------------------------------
# switch
#-------------------------------------------
switch:
#-------------------------------------------
# Локальные реле
#-------------------------------------------
  - platform: gpio
    id: relay_1
    pin: 40
 # - platform: gpio
 #   id: relay_2
 #   pin: 2
 # - platform: gpio
 #   id: relay_3
  #  pin: 1

  - platform: template
    name: Antiburn
    id: switch_antiburn
    icon: mdi:television-shimmer
    optimistic: true
    entity_category: "config"
    turn_on_action:
      - logger.log: "Starting Antiburn"
      - if:
          condition: lvgl.is_paused
          then:
            - lvgl.resume:
            - lvgl.widget.redraw:
            - delay: 1s
      - lvgl.pause:
          show_snow: true
    turn_off_action:
      - logger.log: "Stoping Antiburn"
      - if:
          condition: lvgl.is_paused
          then:
            - lvgl.resume:
            - lvgl.widget.redraw:
            - delay: 1s
            - lvgl.pause:

#-------------------------------------------
# Buttons
#-------------------------------------------
button:
  - platform: restart
    name: "${name} restart"
  - platform: template
    name: "${name} Next page"
    on_press:
      then:
        lvgl.page.next:    

#-------------------------------------------
# Outputs
#-------------------------------------------
output:
  - platform: ledc
    pin: GPIO38
    id: GPIO38
    frequency: 100Hz
    
#-------------------------------------------
# LIGHTS
#
#  value: !lambda return (id(backlight).state)->brightness  *100; -------------------------------------------
light:
  - platform: monochromatic
    output: GPIO38
    name: Backlight
    id: backlight
    on_turn_on:
      lvgl.widget.update:
        id: w_backlight
        text_color: 0xFFFF00
    on_turn_off:
      - lvgl.widget.update:
          id: w_backlight
          text_color: 0xB6B6B6
      - lvgl.pause:
    on_state:
      - lvgl.widget.update:
          id: b_backlight
          state:
            checked: !lambda return id(backlight);
      - lvgl.slider.update:
          id: dimmer_slider
          value: !lambda return id(backlight).remote_values.get_brightness() * 100;
      - logger.log: "Light turned on with previous brightness setting"
#-------------------------------------------
# Number
#-------------------------------------------
number:
  - platform: template
    name: LVGL Screen timeout
    optimistic: true
    id: display_timeout
    unit_of_measurement: "s"
    initial_value: 45
    restore_value: true
    min_value: 10
    max_value: 180
    step: 5
    mode: box
 
#-------------------------------------------
# TOUCHSCREEN
#-------------------------------------------
touchscreen:
  platform: gt911
  transform:
    mirror_x: false
    mirror_y: false
  id: my_touchscreen
  display: my_display
  on_release:
    then:
      - if:
          condition: lvgl.is_paused
          then:
            - lvgl.resume:
            - lvgl.widget.redraw:
            - logger.log: "LVGL resuming"
            - light.turn_on: backlight

#-------------------------------------------
# DISPLAY
#-------------------------------------------
display:
  - platform: st7701s
    id: my_display
    update_interval: never
    auto_clear_enabled: False
    spi_mode: MODE3
    data_rate: 2MHz
    #rotation: 90
    color_order: RGB
    invert_colors: False
    dimensions:
      width: 480
      height: 480
    cs_pin: 39
    de_pin: 18
    hsync_pin: 16
    vsync_pin: 17
    pclk_pin: 21
    pclk_frequency: 12MHz
    pclk_inverted: False
    hsync_pulse_width: 8
    hsync_front_porch: 10
    hsync_back_porch: 20
    vsync_pulse_width: 8
    vsync_front_porch: 10
    vsync_back_porch: 10
    init_sequence:
      - 1
      # Custom sequences are an array, first byte is command, the rest are data.
      - [ 0xFF, 0x77, 0x01, 0x00, 0x00, 0x10 ] # CMD2_BKSEL_BK0
      - [ 0xCD, 0x00 ] # disable MDT flag
    data_pins:
      red:
        - 11        #r1
        - 12        #r2
        - 13        #r3
        - 14        #r4
        - 0         #r5
      green:
        - 8         #g0
        - 20        #g1
        - 3         #g2
        - 46        #g3
        - 9         #g4
        - 10        #g5
      blue:
        - 4         #b1
        - 5         #b2
        - 6         #b3
        - 7         #b4
        - 15        #b5   


#-------------------------------------------
# WEB 51 112 bytes
#-------------------------------------------
web_server:
  port: 80  
  auth:
    username: !secret web_user
    password: !secret web_pass

#-------------------------------------------
# TIME
#-------------------------------------------
time:
  - platform: sntp
    id: sntp_time
    timezone: UTC-3 #Europe/Moscow
    servers: !secret sntp
   # on_time_sync:
   #   - script.execute: time_update_weather
   #   - script.execute: time_update_holl
    #  - script.execute: time_update_kitchen
     # - script.execute: time_update_clock  
    on_time:
      - minutes: 25
        seconds: 0
        then:
          - switch.turn_on: switch_antiburn
      - minutes: 55
        seconds: 0
        then:
          - switch.turn_off: switch_antiburn

    #  - minutes: '*'
     #   seconds: 0
    #    then:
     #     - script.execute: time_update_weather
      #    - script.execute: time_update_holl
      #    - script.execute: time_update_kitchen
      #    - script.execute: time_update_clock
        
#-------------------------------------------   
# LVGL
#-------------------------------------------    
lvgl:
  displays:
    -  my_display
  touchscreens:
    -  my_touchscreen

  on_idle:
    timeout: !lambda "return (id(display_timeout).state * 1000);"
    then:
      - logger.log: "LVGL is idle"
      - light.turn_off: backlight
      - lvgl.pause:

  style_definitions:
    - id: style_line
      line_color: 0x0000FF
      line_width: 8
      line_rounded: true

    - id: header_footer
      bg_color: 0x2F8CD8
      bg_grad_color: 0x005782
      bg_grad_dir: VER
      bg_opa: cover
      border_width: 0
      radius: 0
      pad_all: 0
     # pad_row: 0
     # pad_column: 0
      border_color: 0x0077b3
      text_color: 0xFFFFFF
      width: 100%
      height: 30

  theme:
    button:
      text_font: menu24
      scroll_on_focus: true
      radius: 25
      width: 110
      height: 100
      bg_color: 0x313131
      text_color: 0xB6B6B6
      checked:
        bg_color: 0xCC5E14
        text_color: 0xB6B6B6
    buttonmatrix:
      bg_opa: transp
      border_color: 0x0077b3
      border_width: 0
      text_color: 0xFFFFFF
      pad_all: 0
      items: # set all your btnmatrix buttins to use your custom defined styles and font
        bg_color: 0x2F8CD8
        bg_grad_color: 0x005782
        bg_grad_dir: VER
        bg_opa: cover
        border_color: 0x0077b3
        border_width: 1
        text_color: 0xFFFFFF
        text_font: menu24
        pressed:
          bg_color: 0x006699
          bg_grad_color: 0x00334d
        checked:
          bg_color: 0x1d5f96
          bg_grad_color: 0x03324A
          text_color: 0x005580

    slider:
      border_width: 1
      border_opa: 30%
      bg_color: 0x9c9c9c
      bg_opa: 15%
      indicator:
        bg_color: 0x333333
        bg_grad_color: 0x333333
        bg_opa: COVER
      knob:
        bg_color: 0x444444
        bg_grad_color: 0x444444
        bg_opa: COVER
        border_color: 0x444444
        border_width: 1
        text_color: 0xFFFFFF

  top_layer:
      widgets:
        - obj:
            id: boot_screen
            x: 0
            y: 0
            width: 100%
            height: 100%
            bg_color: 0x000000
            bg_opa: COVER
            radius: 0
            pad_all: 0
            border_width: 0
            widgets:
              - image:
                  align: CENTER
                  src: $background_boot
                  y: -40
              - spinner:
                  align: CENTER
                  y: 95
                  height: 50
                  width: 50
                  spin_time: 1s
                  arc_length: 60deg
                  arc_width: 8
                  indicator:
                    arc_color: 0x18bcf2
                    arc_width: 8
            on_press:
              - lvgl.widget.hide: boot_screen

        - buttonmatrix:
            align: bottom_mid
            styles: header_footer
            pad_all: 0
            outline_width: 0
            id: top_layer
            items:
              styles: header_footer
            rows:
              - buttons:
                - id: page_prev
                  text: "\U000F0141"
                  on_press:
                    then:
                      lvgl.page.previous:
                - id: page_home
                  text: "\U000F06A1"
                  on_press:
                    then:
                      lvgl.page.show: $page_home
                - id: page_next
                  text: "\U000F0142"
                  on_press:
                    then:
                      lvgl.page.next:   
  page_wrap: true