#############################################################################
#----Страничка барометра-----------------------------------------------------
#############################################################################
# Add yaml and copy file esphome/packages/
#  barometr: !include 
#    file: packages/display/barometr.yaml 
#    vars:
#      sensor_temperature: sensor.holl_clock_temperature
#      sensor_pressure: sensor.holl_clock_pressure
# 
#############################################################################

#-------------------------------------------
# SENSOR
#-------------------------------------------    
sensor:
  - platform: homeassistant
    id: barometr_pressure
    entity_id: $sensor_pressure
    on_value:
      then:
        - lvgl.label.update:
            id: barometr_text
            text: 
              format: " %.0f"
              args: ["id(barometr_pressure).state"]

        - lvgl.indicator.update:
            id: barometr_meter
            value: !lambda |- 
              return x;
              
################################################################
      - lvgl.label.update:
          id: display_pressure
          text: 
            format: "$gauge %.0f mmHg"
            args: ["id(barometr_pressure).state"]
          text_color: !lambda |-
            uint16_t vp = (id(barometr_pressure).state);
            switch (vp) {
              case 710 ... 730: return lv_color_hex(0xff0000);
              case 731 ... 740: return lv_color_hex(0xf07c40);
              case 741 ... 760: return lv_color_hex(0x00ff00);
              case 761 ... 770: return lv_color_hex(0xf07c40);
              case 771 ... 800: return lv_color_hex(0xff0000);
              default: return lv_color_hex(0x333333);
            }
################################################################

#-------------------------------------------
# LVGL
#-------------------------------------------
lvgl:
  pages:
# Добавляем на weather barometr
################################################################
    - id: !extend weather
      widgets:
        - button:
            y: 70
            x: 30
            align: LEFT_MID
            bg_opa: TRANSP
            shadow_opa: TRANSP
            width: 180
            height: 40
            widgets:  
              - label:
                  align: LEFT_MID
                  id: display_pressure
                  text: --- mmHg
                  text_font: weather24
                  text_color: 0x808080
            on_press:
              lvgl.page.show: barometr_page
################################################################     
# Вывод на экран 
    - id: barometr_page
      #width: 100%
      bg_color: 0x000000
      #opa: cover
      scrollbar_mode: "OFF"
      scrollable: false
      widgets:
        # Красный
        - line:
            points:
              - 170, 170
              - -70, 410
            line_width: 200
            line_color: 0xF50F34
            line_rounded: false 
        # Желтый
        - line:
            points:
              - 90, 220
              - 120, 0
            line_width: 250
            line_color:  0xe7c12c
            line_rounded: false  
        # Зеленый
        - line:
            points:
              - 170, 110
              - 480, -80
            line_width: 300
            line_color: 0x00ff00 
            line_rounded: false 
        # Желтый
        - line:
            points:
              - 330, 295
              - 482, 0 #+5 -5
            line_width: 220
            line_color: 0xe7c12c
            line_rounded: false 
        # Красный
        - line:
            points:
              - 360, 220
              - 390, 480
            line_color: 0xF50F34
            line_width: 240
            line_rounded: false
         # Белый
        - line:
            points:
              - 105, 585
              - 345, 345
            align: TOP_left
            line_width: 300
            line_color: 0xFFFFFF
            line_rounded: false 
# Шкала
        - meter:
            bg_opa: 0%
            opa: 100%
            #bg_color: color_blue
            shadow_color: color_blue
            shadow_spread: 2
            shadow_width: 25
            shadow_opa: 100%
            border_width: 15
            width: 300
            height: 300
            align: center
            scales:
              - ticks: 
                  count: 101
                  width: 1
                  length: 10
                  color: 0x000000
                  major:
                    stride: 10
                    width: 3
                    length: 20
                    color: 0x000000
                    label_gap: 10
                angle_range: 270
                rotation: 135
                range_from: 0
                range_to: 5
# Индикатор
        - meter:
            width: 200
            height: 200
            align: center
            scales:
              - indicators:
                  - line:
                      id: barometr_meter
                      width: 4
                      color: 0xFF0000
                      r_mod: -15
                      #value: 0
                angle_range: 270
                rotation: 135
                range_from: 700
                range_to: 800
                ticks: 
                  count: 101
                  width: 0
                  length: 0
                  color: 0x000000
                  major:
                    stride: 10
                    width: 0
                    length: 0
                    color: 0x000000
                    label_gap: 8
                    
        - led:
           y: 65
           align: CENTER
           color: 808080
           width: 40
           height: 25         
        - label:
            id: barometr_text
            text: "--"
            text_color: color_violet
            align: CENTER
            y: 65
            
        - label:
            text: $rainy
            text_color: color_blue
            text_font: weather_icons
            align:  LEFT_MID
            y: 120
        - label:
            text:  $cloudy
            text_color: color_white
            text_font: weather_icons
            align: TOP_MID  
            y: -10
        - label:
            y: 120
            text: $sunny
            text_color: color_yellow
            text_font: weather_icons
            align: RIGHT_MID
            
        - spinner:
            width: 245
            height: 245
            align: center
            spin_time: 0s
            arc_length: 0deg
            arc_width: 3
            arc_color: 0x000000
            indicator:
              arc_width: 3
              arc_color: 0x000000

