

#-------------------------------------------
# IMAGE
#-------------------------------------------
image:
  - file: "picture/barometr.jpg"
    id: barometr_image
    resize: 480x480
    type: RGB565
    

#-------------------------------------------
# SENSOR BME68x BSEC2
#-------------------------------------------
bme68x_bsec2_i2c:
  address: 0x77
  model: bme680
  operating_age: 28d
  sample_rate: LP
  supply_voltage: 3.3V
  
    
#-------------------------------------------
# SENSOR
#-------------------------------------------
#-------------------------------------------
# SENSOR
#-------------------------------------------
sensor:
  - platform: bme68x_bsec2
    temperature:
      name: "Temperature"
      id: bme680_t
      filters:
      - calibrate_linear:
        - 0.0 -> 0.0
        - 26.7 -> 24.7
      - delta: 0.2
      on_value:
        - lvgl.indicator.update:
            id: temperatura_hand
            value: !lambda |- 
              return x;
    pressure:
      name: "Pressure"
      id: bme680_p
      filters:
      - delta: 1
      on_value:
        - lvgl.indicator.update:
            id: barometr_hand
            value: !lambda |- 
              return x;
        - lvgl.indicator.update:
            id: barometr_hand_z
            value: !lambda |- 
              return x;
    humidity:
      name: "Humidity"
      id: bme680_h
      filters:
      - calibrate_linear:
        - 0.0 -> 0.0
        - 52 -> 54.7
      - delta: 1
    iaq:
      name: "IAQ"
      id: bme680_iaq
      filters:
      - delta: 5
    iaq_accuracy:
      name: " IAQ Accuracy"
      filters:
      - delta: 5
    co2_equivalent:
      name: "CO₂"
      id: bme680_co2
      filters:
      - delta: 5
    breath_voc_equivalent:
      name: "VOC"
      id: bme680_voc
      filters:
      - delta: 5

        
  - platform: absolute_humidity
    name: "Absolute Humidity"
    temperature: bme680_t
    humidity: bme680_h    
    filters:
    - delta: 0.5        

  - platform: template # Pressure 1h
    name: "${name} pressure old 1h"
    id: pressure_1h
    update_interval: never
    device_class: pressure


  - platform: template # Pressure 2h
    name: "${name} pressure old 2h"
    id: pressure_2h
    update_interval: never
    device_class: pressure


  - platform: template # Pressure 3h
    name: "${name} pressure old 3h"
    id: pressure_3h
    update_interval: never
    device_class: pressure
    on_value:
      - lvgl.indicator.update:
          id: barometr_hand_3h
          value: !lambda |- 
            return x;
      - lvgl.indicator.update:
          id: barometr_hand_3hz
          value: !lambda |- 
            return x;
            
            
#-------------------------------------------
# TEXT SENSOR
#-------------------------------------------
text_sensor:
  - platform: bme68x_bsec2
    iaq_accuracy:
      name: "IAQ Accuracy"
  - platform: template
    name: "IAQ Classification"
    icon: "mdi:checkbox-marked-circle-outline"
    lambda: |-
      uint16_t var = (id(bme680_iaq).state);
      switch (var) {
        case 0 ... 50: return std::string("Отлично");
        case 51 ... 100: return std::string("Хорошо");
        case 101 ... 150: return std::string("Слегка загрязненный");
        case 151 ... 200: return std::string("Умеренно загрязненный");
        case 201 ... 250: return std::string("Слегка загрязненный");
        case 251 ... 300: return std::string("Загрязненный");
        case 301 ... 350: return std::string("Сильно загрязненный");
        case 351 ... 500: return std::string("Черезвычайно загрязненный"); 
        default: return std::string("error");
      }  

         
            
#-------------------------------------------
# TIME
#-------------------------------------------
time:
  - id: !extend sntp_time
    on_time_sync:
    - lambda: !lambda |-
        id(pressure_3h).publish_state(id(bme680_p).state);
        id(pressure_2h).publish_state(id(bme680_p).state);
        id(pressure_1h).publish_state(id(bme680_p).state);
  
    on_time:
      - hours: '*'
        minutes: 50
        seconds: 0
        then:
          lambda: !lambda |-
            id(pressure_3h).publish_state(id(pressure_2h).state);
            id(pressure_2h).publish_state(id(pressure_1h).state);
            id(pressure_1h).publish_state(id(bme680_p).state);     

#-------------------------------------------
# LVGL
#-------------------------------------------
lvgl:
  pages:
    - id: barometr_page    
      width: 100%
      bg_color: 0x000000
      bg_opa: cover
      scrollbar_mode: "OFF"
      widgets:
        - image:
            align: CENTER
            src: barometr_image
        - obj:
            bg_opa: TRANSP
            border_opa: TRANSP
            width: 480
            height: 480
            align: CENTER
            scrollbar_mode: "OFF"
            scrollable: false
            widgets:
            #######################
              - meter:
                  border_side: none
                  height: 480
                  width: 480
                  align: CENTER
                  bg_opa: TRANSP
                  text_color: 0xFFFFFF
                  scales:
                    - indicators:
                        - line:
                            id: barometr_hand_3h
                            width: 3
                            color: 0xE0E0E0 #white
                            r_mod: -15
                      rotation: 120
                      angle_range: 300 # Угол между началом и концом
                      range_from: 920 #690 # Минимальное значение
                      range_to: 1080 #810  # Максимальное значение
                      ticks: 
                        count: 0 
                        
                    - indicators:
                        - line:
                            id: barometr_hand_3hz
                            width: 7
                            color: 0xE0E0E0 #white
                            r_mod: -150
                      rotation: 300
                      angle_range: 300 # Угол между началом и концом
                      range_from: 920 #690 # Минимальное значение
                      range_to: 1080 #810  # Максимальное значение
                      ticks: 
                        count: 0

                    - indicators:
                        - line:
                            id: barometr_hand
                            width: 3
                            color: 0xFF0000 # red 0xE0E0E0 #white
                            r_mod: -15
                      rotation: 120
                      angle_range: 300 # Угол между началом и концом
                      range_from: 920 #690 # Минимальное значение
                      range_to: 1080 #810  # Максимальное значение
                      ticks: 
                        count: 0 

                    - indicators:
                        - line:
                            id: barometr_hand_z
                            width: 7
                            color: 0xFF0000 # red 0xE0E0E0 #white
                            r_mod: -150
                      rotation: 300
                      angle_range: 300 # Угол между началом и концом
                      range_from: 920 #690 # Минимальное значение
                      range_to: 1080 #810  # Максимальное значение
                      ticks: 
                        count: 0
      
              - meter:
                  border_side: none
                  height: 100
                  width: 100
                  y: 180
                  align: CENTER
                  bg_opa: TRANSP
                  text_color: 0xFFFFFF
                  scales:
                    - indicators:
                        - line:
                            id: temperatura_hand
                            width: 3
                            color: 0xFF0000 # red 0xE0E0E0 #white
                            r_mod: 30
                      rotation: 180
                      angle_range: 180 # Угол между началом и концом
                      range_from: -10 # Минимальное значение
                      range_to: 50  # Максимальное значение
                      ticks: 
                        count: 0 

              - led:
                  align: CENTER
                  color: 0xFF0000
                  width: 15
                  height: 15