#-------------------------------------------
# IMAGE
#-------------------------------------------
image:
  - file: "picture/barometr.jpg"
    id: barometr_image
    resize: 450x450
    type: RGB565
    
#-------------------------------------------
# SENSOR
#-------------------------------------------
sensor:
  - platform: homeassistant
    id:  barometr_temperature
    entity_id: $sensor_temperature
    on_value:
      - lvgl.indicator.update:
          id: temperatura_hand
          value: !lambda |- 
            return x;
  - platform: homeassistant
    id:  barometr_pressure
    entity_id: $sensor_pressure
    on_value:
      - lvgl.indicator.update:
          id: barometr_hand
          value: !lambda |- 
            return x * 0.75;
      - lvgl.indicator.update:
          id: barometr_hand_z
          value: !lambda |- 
            return x * 0.75;

  - platform: template # Pressure 1h
    name: "${name} pressure old 1h"
    id: pressure_1h
    update_interval: never
    device_class: pressure


  - platform: template # Pressure 2h
    name: "${name} pressure old 2h"
    id: pressure_2h
    update_interval: never
    device_class: pressure


  - platform: template # Pressure 3h
    name: "${name} pressure old 3h"
    id: pressure_3h
    update_interval: never
    device_class: pressure
    on_value:
      - lvgl.indicator.update:
          id: barometr_hand_3h
          value: !lambda |- 
            return x;
      - lvgl.indicator.update:
          id: barometr_hand_3hz
          value: !lambda |- 
            return x;
            
#-------------------------------------------
# TIME
#-------------------------------------------
time:
  - platform: sntp
    on_time_sync:
    - lambda: !lambda |-
        id(pressure_3h).publish_state(id(barometr_pressure).state);
        id(pressure_2h).publish_state(id(barometr_pressure).state);
        id(pressure_1h).publish_state(id(barometr_pressure).state);
    on_time:
      - hours: '*'
        minutes: 50
        seconds: 0
        then:
          lambda: !lambda |-
            id(pressure_3h).publish_state(id(pressure_2h).state);
            id(pressure_2h).publish_state(id(pressure_1h).state);
            id(pressure_1h).publish_state(id(barometr_pressure).state);
    
#-------------------------------------------
lvgl:
  pages:
    - id: barometr_page
     # layout: flex
     # flex_flow: COLUMN_WRAP
      width: 100%
      bg_color: 0x000000
      bg_opa: cover
      pad_all: 5 
      widgets:
        - obj: # barometer container
            height: 450
            width: 480
            border_side: none
            bg_color: 0x000000
            widgets:
              - image:
                  align: CENTER
                  src: barometr_image
                  id: im_barometr
                  radius: 20
                  clip_corner: true

              - meter:
                  border_side: none
                  height: 450
                  width: 450
                  align: center
                  bg_opa: TRANSP
                  text_color: 0xFFFFFF
                  scales:
                    - indicators:
                        - line:
                            id: barometr_hand_3h
                            width: 3
                            color: 0xE0E0E0 #white
                            r_mod: -15
                      rotation: 120
                      angle_range: 300 # Угол между началом и концом
                      range_from: 690 # Минимальное значение
                      range_to: 810  # Максимальное значение
                      ticks: 
                        count: 0 
                        
                    - indicators:
                        - line:
                            id: barometr_hand_3hz
                            width: 7
                            color: 0xE0E0E0 #white
                            r_mod: -150
                      rotation: 300
                      angle_range: 300 # Угол между началом и концом
                      range_from: 690 # Минимальное значение
                      range_to: 810     
                      ticks: 
                        count: 0

              - meter:
                  border_side: none
                  height: 450
                  width: 450
                  align: center
                  bg_opa: TRANSP
                  text_color: 0xFFFFFF
                  scales:
                    - indicators:
                        - line:
                            id: barometr_hand
                            width: 3
                            color: 0xFF0000 # red 0xE0E0E0 #white
                            r_mod: -15
                      rotation: 120
                      angle_range: 300 # Угол между началом и концом
                      range_from: 690 # Минимальное значение
                      range_to: 810  # Максимальное значение
                      ticks: 
                        count: 0 

                    - indicators:
                        - line:
                            id: barometr_hand_z
                            width: 7
                            color: 0xFF0000 # red 0xE0E0E0 #white
                            r_mod: -150
                      rotation: 300
                      angle_range: 300 # Угол между началом и концом
                      range_from: 690 # Минимальное значение
                      range_to: 810    
                      ticks: 
                        count: 0 
                  widgets:
                    - meter:
                        x: 155
                        y: 325
                        height: 100
                        width: 100
                        bg_opa: 0%
                        border_side: none
                        text_color: 0xFFFFFF
                        scales:
                          - indicators:
                            - line:
                                id: temperatura_hand
                                width: 3
                                color: 0xFF0000 # red 0xE0E0E0 #white
                                r_mod: 30
                            rotation: 180
                            angle_range: 180 # Угол между началом и концом
                            range_from: -10 # Минимальное значение
                            range_to: 50  # Максимальное значение
                            ticks: 
                              count: 0 

              - led:
                  align: CENTER
                  color: 0xFF0000
                  width: 15
                  height: 15