#############################################################################
#----Страничка с пыльцой березы----------------------------------------------
#############################################################################
# Add yaml and copy file esphome/packages/
#packages:
#  birch: !include
#    file: packages/birch.yaml
#    vars:
#      sensor_birch: sensor.iaroslavskaia_birch_pollen_index


#-------------------------------------------
# IMAGE
#-------------------------------------------
image:
  - file: "picture/birch.jpg"
    id: birch_img
    resize: 60x60
    type: RGB565 
#-------------------------------------------
# SENSOR
#-------------------------------------------    
sensor:
  - platform: homeassistant
    id: birch_index
    entity_id: $sensor_birch
    filters:
      - filter_out: nan
    on_value:
      then:
        - lvgl.label.update:
            id: birch_text
            text: 
              format: " %.0f"
              args: ["id(birch_index).state"]

        - lvgl.indicator.update:
            id: birch_meter
            value: !lambda |- 
              return x;
        - lambda: |-
            uint8_t vbirch= (id(birch_index).state);
            switch (vbirch) {
              case 0 ... 2: return id(birch_class).publish_state("Низкое содержание");
              case 3: return id(birch_class).publish_state("Умеренное содержание");
              case 4: return id(birch_class).publish_state("Высокое содержание");
              case 5: return id(birch_class).publish_state("Очень высокое содержание");
              default: return id(birch_class).publish_state("n/a");
            }
              
################################################################
        - lvgl.label.update:
            id: display_birch
            text: 
              format: "$tree_outline %.0f "
              args: ["id(birch_index).state"]
            text_color: !lambda |-
              uint16_t vbirch = (id(birch_index).state);
              switch (vbirch) {
                case 0 ... 1: return lv_color_hex(0x00ff00);
                case 2: return lv_color_hex(0xe7c12c);
                case 3: return lv_color_hex(0xFFBB33);
                case 4: return lv_color_hex(0xff6600);
                case 5: return lv_color_hex(0xff0000);
                default: return lv_color_hex(0x333333);
              } 
################################################################

#-------------------------------------------
# TEXT SENSOR
#-------------------------------------------
text_sensor:             
  - platform: template
    id: birch_class
    on_value:
      then:
         - lvgl.label.update:
            id: display_birch_class
            text: !lambda |- 
              return x;            
 
#-------------------------------------------
# LVGL
#-------------------------------------------
lvgl:
  pages:
################################################################
# Добавляем на weather birch
    - id: !extend weather
      widgets:
        - button:
            y: 130
            x: 140
            align: LEFT_MID
            bg_opa: TRANSP
            shadow_opa: TRANSP
            width: 180
            height: 40
            widgets:  
              - label:
                  align: LEFT_MID
                  id: display_birch
                  text: --
                  text_font: weather24
                  text_color: 0x808080
            on_press:
              lvgl.page.show: birch_page
              
# Вывод на экран 
    - id: birch_page
      #width: 100%
      bg_color: 0x000000
      #opa: cover
      scrollbar_mode: "OFF"
      scrollable: false
      widgets:
        - canvas: 
            width: 480
            height: 480
            id: birch_fon
            on_boot:
            # Зеленый
              - lvgl.canvas.draw_polygon:
                  id: birch_fon
                  points:
                    - 240, 240
                    - 0, 480
                    - 0, 200
                    - 240, 240
                  bg_color: 0x00ff00
            # Желтый      
              - lvgl.canvas.draw_polygon:
                  id: birch_fon
                  points:
                    - 240, 240
                    - 0, 200
                    - 0, 0
                    - 120, 0  
                    - 240, 240           
                  bg_color: 0xe7c12c
            # Оранжевый      
              - lvgl.canvas.draw_polygon:
                  id: birch_fon
                  points:
                    - 240, 240
                    - 120, 0
                    - 360, 0
                    - 240, 240           
                  bg_color: 0xffa500
            # Красный      
              - lvgl.canvas.draw_polygon:
                  id: birch_fon
                  points:
                    - 240, 240
                    - 360, 0
                    - 480, 0   
                    - 480, 200
                    - 240, 240           
                  bg_color: 0xF50F34   
         # Фиолетовый
              - lvgl.canvas.draw_polygon:
                  id: birch_fon
                  points:
                    - 240, 240
                    - 480, 200
                    - 480, 480   
                    - 240, 240           
                  bg_color: 0xA63DC2  
         # Белый
              - lvgl.canvas.draw_polygon:
                  id: birch_fon
                  points:
                    - 240, 240
                    - 480, 480
                    - 0, 480   
                    - 240, 240           
                  bg_color: 0xffffff
# Шкала
        - meter:
            bg_opa: 0%
            opa: 100%
            #bg_color: color_blue
            shadow_color: color_blue
            shadow_spread: 2
            shadow_width: 25
            shadow_opa: 100%
            border_width: 15
            width: 300
            height: 300
            align: center
            scales:
              - ticks: 
                  count: 11
                  width: 2
                  length: 10
                  color: 0x000000
                  major:
                    stride: 2
                    width: 3
                    length: 20
                    color: 0x000000
                    label_gap: 10
                angle_range: 270
                rotation: 135
                range_from: 0
                range_to: 5
# Индикатор
        - meter:
            width: 200
            height: 200
            align: center
            scales:
              - indicators:
                  - line:
                      id: birch_meter
                      width: 4
                      color: 0xFF0000
                      r_mod: -15
                      value: 0
                angle_range: 270
                rotation: 135
                range_from: 0
                range_to: 5
                ticks: 
                  count: 6
                  width: 0
                  length: 0
                  color: 0x000000
                  major:
                    stride: 1
                    width: 0
                    length: 0
                    color: 0x000000
                    label_gap: 8
                    
        - led:
           y: 65
           align: CENTER
           color: 808080
           width: 40
           height: 25         
        - label:
            id: birch_text
            text: "--"
            text_color: color_violet
            align: CENTER
            y: 65
                  
        - spinner:
            width: 245
            height: 245
            align: center
            spin_time: 0s
            arc_length: 0deg
            arc_width: 3
            arc_color: 0x000000
            indicator:
              arc_width: 3
              arc_color: 0x000000
              
        - label:
            id: display_birch_class
            text_color: color_white
            text: "нет"
            text_font: roboto36
            align: TOP_MID 

        - label:
            text_color: color_white
            text: пыльцы березы
            text_font: roboto36
            align: TOP_MID 
            y: 50
            
        - image:
            align: CENTER
            src: birch_img
            y: 180
            bg_color: 0xFFFFFF
            bg_image_opa: 100% 
