#########################
#     #     #     #     #
# 0_0 # 0_1 # 0_2 # 0_3 #
#     #     #     #     #
#########################
#     #     #     #     #
#     #     #     #     #
# 1_0 # 1_1 # 1_2 # 1_3 #
#     #     #     #     #
#     #     #     #     #
#########################
#     #     #     #     #
# 2_0 # 2_1 # 2_2 # 2_3 #
#     #     #     #     #
#########################

font:
  - file: 'font/materialdesignicons-webfont.ttf' # http://materialdesignicons.com/cdn/7.4.47/ 
    id: button12_48
    size: 48
    bpp: 4
    glyphs: [
      $button12_icon_0_0,
      $button12_icon_0_1,
      $button12_icon_0_2,
      $button12_icon_0_3,
      $button12_icon_1_0,
      $button12_icon_1_1,
      $button12_icon_1_2,
      $button12_icon_1_3,
      $button12_icon_2_0,
      $button12_icon_2_1,
      $button12_icon_2_2,
      $button12_icon_2_3
    ]      
    
 
#-------------------------------------------
# Binary sensor
#-------------------------------------------
binary_sensor:
#-------------------------------------------
# 0 Ряд
#-------------------------------------------
  - platform: homeassistant
    name: bin_button12_icon_0_0
    entity_id: $button12_entity_0_0
    publish_initial_state: true
    #internal: true
    on_state:
      then:
        lvgl.widget.update:
          id: b_button12_0_0
          state:
            checked: !lambda return x;
    on_press:
      lvgl.widget.update:
        id: w_button12_0_0
        text_color: 0xFFFF00
    on_release:
      lvgl.widget.update:
        id: w_button12_0_0
        text_color: 0xB6B6B6
####################################
  - platform: homeassistant
    name: bin_button12_icon_0_1
    entity_id: $button12_entity_0_1
    publish_initial_state: true
    #internal: true
    on_state:
      then:
        lvgl.widget.update:
          id: b_button12_0_1
          state:
            checked: !lambda return x;
    on_press:
      lvgl.widget.update:
        id: w_button12_0_1
        text_color: 0xFFFF00
    on_release:
      lvgl.widget.update:
        id: w_button12_0_1
        text_color: 0xB6B6B6
####################################
  - platform: homeassistant
    name: bin_button12_icon_0_2
    entity_id: $button12_entity_0_2
    publish_initial_state: true
    #internal: true
    on_state:
      then:
        lvgl.widget.update:
          id: b_button12_0_2
          state:
            checked: !lambda return x;
    on_press:
      lvgl.widget.update:
        id: w_button12_0_2
        text_color: 0xFFFF00
    on_release:
      lvgl.widget.update:
        id: w_button12_0_2
        text_color: 0xB6B6B6
####################################
  - platform: homeassistant
    name: bin_button12_icon_0_3
    entity_id: $button12_entity_0_3
    publish_initial_state: true
    #internal: true
    on_state:
      then:
        lvgl.widget.update:
          id: b_button12_0_3
          state:
            checked: !lambda return x;
    on_press:
      lvgl.widget.update:
        id: w_button12_0_3
        text_color: 0xFFFF00
    on_release:
      lvgl.widget.update:
        id: w_button12_0_3
        text_color: 0xB6B6B6


#-------------------------------------------
# 1 Ряд
#-------------------------------------------
  - platform: homeassistant
    name: bin_button12_icon_1_0
    entity_id: $button12_entity_1_0
    publish_initial_state: true
    #internal: true
    on_state:
      then:
        lvgl.widget.update:
          id: b_button12_1_0
          state:
            checked: !lambda return x;
    on_press:
      lvgl.widget.update:
        id: w_button12_1_0
        text_color: 0xFFFF00
    on_release:
      lvgl.widget.update:
        id: w_button12_1_0
        text_color: 0xB6B6B6
####################################
  - platform: homeassistant
    name: bin_button12_icon_1_1
    entity_id: $button12_entity_1_1
    publish_initial_state: true
    #internal: true
    on_state:
      then:
        lvgl.widget.update:
          id: b_button12_1_1
          state:
            checked: !lambda return x;
    on_press:
      lvgl.widget.update:
        id: w_button12_1_1
        text_color: 0xFFFF00
    on_release:
      lvgl.widget.update:
        id: w_button12_1_1
        text_color: 0xB6B6B6
####################################
  - platform: homeassistant
    name: bin_button12_icon_1_2
    entity_id: $button12_entity_1_2
    publish_initial_state: true
    #internal: true
    on_state:
      then:
        lvgl.widget.update:
          id: b_button12_1_2
          state:
            checked: !lambda return x;
    on_press:
      lvgl.widget.update:
        id: w_button12_1_2
        text_color: 0xFFFF00
    on_release:
      lvgl.widget.update:
        id: w_button12_1_2
        text_color: 0xB6B6B6
####################################
  - platform: homeassistant
    name: bin_button12_icon_1_3
    entity_id: $button12_entity_1_3
    publish_initial_state: true
    #internal: true
    on_state:
      then:
        lvgl.widget.update:
          id: b_button12_1_3
          state:
            checked: !lambda return x;
    on_press:
      lvgl.widget.update:
        id: w_button12_1_3
        text_color: 0xFFFF00
    on_release:
      lvgl.widget.update:
        id: w_button12_1_3
        text_color: 0xB6B6B6

#-------------------------------------------
# 2 Ряд
#-------------------------------------------
  - platform: homeassistant
    name: bin_button12_icon_2_0
    entity_id: $button12_entity_2_0
    publish_initial_state: true
    #internal: true
    on_state:
      then:
        lvgl.widget.update:
          id: b_button12_2_0
          state:
            checked: !lambda return x;
    on_press:
      lvgl.widget.update:
        id: w_button12_2_0
        text_color: 0xFFFF00
    on_release:
      lvgl.widget.update:
        id: w_button12_2_0
        text_color: 0xB6B6B6
####################################
  - platform: homeassistant
    name: bin_button12_icon_2_1
    entity_id: $button12_entity_2_1
    publish_initial_state: true
    #internal: true
    on_state:
      then:
        lvgl.widget.update:
          id: b_button12_2_1
          state:
            checked: !lambda return x;
    on_press:
      lvgl.widget.update:
        id: w_button12_2_1
        text_color: 0xFFFF00
    on_release:
      lvgl.widget.update:
        id: w_button12_2_1
        text_color: 0xB6B6B6
####################################
  - platform: homeassistant
    name: bin_button12_icon_2_2
    entity_id: $button12_entity_2_2
    publish_initial_state: true
    #internal: true
    on_state:
      then:
        lvgl.widget.update:
          id: b_button12_2_2
          state:
            checked: !lambda return x;
    on_press:
      lvgl.widget.update:
        id: w_button12_2_2
        text_color: 0xFFFF00
    on_release:
      lvgl.widget.update:
        id: w_button12_2_2
        text_color: 0xB6B6B6
####################################
  - platform: homeassistant
    name: bin_button12_icon_2_3
    entity_id: $button12_entity_2_3
    publish_initial_state: true
    #internal: true
    on_state:
      then:
        lvgl.widget.update:
          id: b_button12_2_3
          state:
            checked: !lambda return x;
    on_press:
      lvgl.widget.update:
        id: w_button12_2_3
        text_color: 0xFFFF00
    on_release:
      lvgl.widget.update:
        id: w_button12_2_3
        text_color: 0xB6B6B6



#-------------------------------------------
# LVGL
#-------------------------------------------
lvgl:
  pages:
    - id: button12_page     
      width: 100%
      bg_color: 0x000000
      bg_opa: cover
      widgets:
        - image:
            align: TOP_LEFT
            src: $background_button12
        - obj:
            bg_opa: TRANSP
            border_opa: TRANSP
            width: 480
            height: 460
            align: TOP_LEFT
            x: 0
            y: 0
            layout:
              pad_row: 10
              pad_column: 10
              type: GRID
              grid_columns: [FR(1), FR(1), FR(1), FR(1)]
              grid_rows: [FR(1), FR(1), FR(1), FR(1)]
            widgets:
            ########################
              - button:
                  checkable: $button12_checkable_0_0
                  id: b_button12_0_0
                  grid_cell_row_pos: 0 #Позиция ряд
                  grid_cell_column_pos: 0 #Позиция колонка
                  grid_cell_x_align: STRETCH
                  grid_cell_y_align: STRETCH
                  grid_cell_row_span: 1 #Занять ячеек в ряде
                  grid_cell_column_span: 1 #Занять ячеек в колонке
                  bg_opa: 35%
                  widgets:
                    - label:
                        text_font: button12_48
                        align: center
                        text: $button12_icon_0_0
                        id: w_button12_0_0
                  on_click:
                    homeassistant.action:
                      action: $button12_action_0_0
                      data:
                        entity_id: $button12_entity_0_0        
                    
              - button:
                  checkable: $button12_checkable_0_1
                  id: b_button12_0_1
                  grid_cell_row_pos: 0 #Позиция ряд
                  grid_cell_column_pos: 1 #Позиция колонка
                  grid_cell_x_align: STRETCH
                  grid_cell_y_align: STRETCH
                  grid_cell_row_span: 1 #Занять ячеек в ряде
                  grid_cell_column_span: 1 #Занять ячеек в колонке
                  bg_opa: 35%
                  widgets:
                    - label:
                        text_font: button12_48
                        align: center
                        text: $button12_icon_0_1
                        id: w_button12_0_1
                  on_click:
                    homeassistant.action:
                      action: $button12_action_0_1
                      data:
                        entity_id: $button12_entity_0_1   
            
              - button:
                  checkable: $button12_checkable_0_2
                  id: b_button12_0_2
                  grid_cell_row_pos: 0 #Позиция ряд
                  grid_cell_column_pos: 2 #Позиция колонка
                  grid_cell_x_align: STRETCH
                  grid_cell_y_align: STRETCH
                  grid_cell_row_span: 1 #Занять ячеек в ряде
                  grid_cell_column_span: 1 #Занять ячеек в колонке
                  bg_opa: 35%
                  widgets:
                    - label:
                        text_font: button12_48
                        align: center
                        text: $button12_icon_0_2
                        id: w_button12_0_2
                  on_click:
                    homeassistant.action:
                      action: $button12_action_0_2
                      data:
                        entity_id: $button12_entity_0_2  
            
              - button:
                  checkable: $button12_checkable_0_3
                  id: b_button12_0_3
                  grid_cell_row_pos: 0 #Позиция ряд
                  grid_cell_column_pos: 3 #Позиция колонка
                  grid_cell_x_align: STRETCH
                  grid_cell_y_align: STRETCH
                  grid_cell_row_span: 1 #Занять ячеек в ряде
                  grid_cell_column_span: 1 #Занять ячеек в колонке
                  bg_opa: 35%
                  widgets:
                    - label:
                        text_font: button12_48
                        align: center
                        text: $button12_icon_0_3
                        id: w_button12_0_3
                  on_click:
                    homeassistant.action:
                      action: $button12_action_0_3
                      data:
                        entity_id: $button12_entity_0_3  
                        
            
            ########################
              - button:
                  checkable: $button12_checkable_1_0
                  id: b_button12_1_0
                  grid_cell_row_pos: 1 #Позиция ряд
                  grid_cell_column_pos: 0 #Позиция колонка
                  grid_cell_x_align: STRETCH
                  grid_cell_y_align: STRETCH
                  grid_cell_row_span: 2 #Занять ячеек в ряде
                  grid_cell_column_span: 1 #Занять ячеек в колонке
                  bg_opa: 35%
                  widgets:
                    - label:
                        text_font: button12_48
                        align: center
                        text: $button12_icon_1_0
                        id: w_button12_1_0
                  on_click:
                    homeassistant.action:
                      action: $button12_action_1_0
                      data:
                        entity_id: $button12_entity_1_0        
                    
              - button:
                  checkable: $button12_checkable_1_1
                  id: b_button12_1_1
                  grid_cell_row_pos: 1 #Позиция ряд
                  grid_cell_column_pos: 1 #Позиция колонка
                  grid_cell_x_align: STRETCH
                  grid_cell_y_align: STRETCH
                  grid_cell_row_span: 2 #Занять ячеек в ряде
                  grid_cell_column_span: 1 #Занять ячеек в колонке
                  bg_opa: 35%
                  widgets:
                    - label:
                        text_font: button12_48
                        align: center
                        text: $button12_icon_1_1
                        id: w_button12_1_1
                  on_click:
                    homeassistant.action:
                      action: $button12_action_1_1
                      data:
                        entity_id: $button12_entity_1_1   
            
              - button:
                  checkable: $button12_checkable_1_2
                  id: b_button12_1_2
                  grid_cell_row_pos: 1 #Позиция ряд
                  grid_cell_column_pos: 2 #Позиция колонка
                  grid_cell_x_align: STRETCH
                  grid_cell_y_align: STRETCH
                  grid_cell_row_span: 2 #Занять ячеек в ряде
                  grid_cell_column_span: 1 #Занять ячеек в колонке
                  bg_opa: 35%
                  widgets:
                    - label:
                        text_font: button12_48
                        align: center
                        text: $button12_icon_1_2
                        id: w_button12_1_2
                  on_click:
                    homeassistant.action:
                      action: $button12_action_1_2
                      data:
                        entity_id: $button12_entity_1_2  
            
              - button:
                  checkable: $button12_checkable_1_3
                  id: b_button12_1_3
                  grid_cell_row_pos: 1 #Позиция ряд
                  grid_cell_column_pos: 3 #Позиция колонка
                  grid_cell_x_align: STRETCH
                  grid_cell_y_align: STRETCH
                  grid_cell_row_span: 2 #Занять ячеек в ряде
                  grid_cell_column_span: 1 #Занять ячеек в колонке
                  bg_opa: 35%
                  widgets:
                    - label:
                        text_font: button12_48
                        align: center
                        text: $button12_icon_1_3
                        id: w_button12_1_3
                  on_click:
                    homeassistant.action:
                      action: $button12_action_1_3
                      data:
                        entity_id: $button12_entity_1_3     
                        

            ########################
              - button:
                  checkable: $button12_checkable_2_0
                  id: b_button12_2_0
                  grid_cell_row_pos: 3 #Позиция ряд
                  grid_cell_column_pos: 0 #Позиция колонка
                  grid_cell_x_align: STRETCH
                  grid_cell_y_align: STRETCH
                  grid_cell_row_span: 1 #Занять ячеек в ряде
                  grid_cell_column_span: 1 #Занять ячеек в колонке
                  bg_opa: 35%
                  widgets:
                    - label:
                        text_font: button12_48
                        align: center
                        text: $button12_icon_2_0
                        id: w_button12_2_0
                  on_click:
                    homeassistant.action:
                      action: $button12_action_2_0
                      data:
                        entity_id: $button12_entity_2_0        
                    
              - button:
                  checkable: $button12_checkable_2_1
                  id: b_button12_2_1
                  grid_cell_row_pos: 3 #Позиция ряд
                  grid_cell_column_pos: 1 #Позиция колонка
                  grid_cell_x_align: STRETCH
                  grid_cell_y_align: STRETCH
                  grid_cell_row_span: 1 #Занять ячеек в ряде
                  grid_cell_column_span: 1 #Занять ячеек в колонке
                  bg_opa: 35%
                  widgets:
                    - label:
                        text_font: button12_48
                        align: center
                        text: $button12_icon_2_1
                        id: w_button12_2_1
                  on_click:
                    homeassistant.action:
                      action: $button12_action_2_1
                      data:
                        entity_id: $button12_entity_2_1   
            
              - button:
                  checkable: $button12_checkable_2_2
                  id: b_button12_2_2
                  grid_cell_row_pos: 3 #Позиция ряд
                  grid_cell_column_pos: 2 #Позиция колонка
                  grid_cell_x_align: STRETCH
                  grid_cell_y_align: STRETCH
                  grid_cell_row_span: 1 #Занять ячеек в ряде
                  grid_cell_column_span: 1 #Занять ячеек в колонке
                  bg_opa: 35%
                  widgets:
                    - label:
                        text_font: button12_48
                        align: center
                        text: $button12_icon_2_2
                        id: w_button12_2_2
                  on_click:
                    homeassistant.action:
                      action: $button12_action_2_2
                      data:
                        entity_id: $button12_entity_2_2  
            
              - button:
                  checkable: $button12_checkable_2_3
                  id: b_button12_2_3
                  grid_cell_row_pos: 3 #Позиция ряд
                  grid_cell_column_pos: 3 #Позиция колонка
                  grid_cell_x_align: STRETCH
                  grid_cell_y_align: STRETCH
                  grid_cell_row_span: 1 #Занять ячеек в ряде
                  grid_cell_column_span: 1 #Занять ячеек в колонке
                  bg_opa: 35%
                  widgets:
                    - label:
                        text_font: button12_48
                        align: center
                        text: $button12_icon_2_3
                        id: w_button12_2_3
                  on_click:
                    homeassistant.action:
                      action: $button12_action_2_3
                      data:
                        entity_id: $button12_entity_2_3  
