substitutions:
  icons12_0_0: "\U000F18DE" # ceiling_light_multiple_outline
  icons12_0_1: "󱊺" #string_lights
  icons12_0_2: "󱍖" #television_ambient_light
  icons12_0_3: "󱦇" #light_flood_down
  
  icons12_1_0: "󰯪" #alarm_light_on
  icons12_1_1: "󱠝" #countertop_outline
  icons12_1_2: "󰟴" #television
  icons12_1_3: "󰦠" #shower:
  
  icons12_2_0: "󱞓" #chandelier
  icons12_2_1: "󰠠" #lightning_bolt_circle
  icons12_2_2: "󱇜" #window_open_variant
  icons12_2_3: "󰣳" #nas
  

# Кнопки 0 ряд !!!!!!! ИКОНКИ НЕ ДОЛЖНЫ повторятся !!!!!!!!!!
  button12_icon_0_0: $icons12_0_0
  button12_entity_0_0: light.holl_led_0

  button12_icon_0_1: $icons12_0_1
  button12_entity_0_1: light.holl_led_1
  
  button12_icon_0_2: $icons12_0_2
  button12_entity_0_2: light.holl_led_2

  button12_icon_0_3: $icons12_0_3
  button12_entity_0_3: light.holl_led_3
  
# Кнопки 1 ряд
  button12_icon_1_0: $icons12_1_0
  button12_entity_1_0: light.holl_led_4

  button12_icon_1_1: $icons12_1_1
  button12_entity_1_1: light.holl_led_5
  
  button12_icon_1_2: $icons12_1_2
  button12_entity_1_2: light.holl_led_6

  button12_icon_1_3: $icons12_1_3
  button12_entity_1_3: light.holl_led_7

# Кнопки 2 ряд
  button12_icon_2_0: $icons12_2_0
  button12_entity_2_0: light.holl_led_8

  button12_icon_2_1: $icons12_2_1
  button12_entity_2_1: light.holl_led_9
  
  button12_icon_2_2: $icons12_2_2
  button12_entity_2_2: light.holl_led_10

  button12_icon_2_3: $icons12_2_3
  button12_entity_2_3: light.holl_led_11
  
  
font:
  - file: 'font/materialdesignicons-webfont.ttf' # http://materialdesignicons.com/cdn/7.4.47/ 
    id: button12_48
    size: 48
    bpp: 4
    glyphs: [
      $button12_icon_0_0,
      $button12_icon_0_1,
      $button12_icon_0_2,
      $button12_icon_0_3,
      $button12_icon_1_0,
      $button12_icon_1_1,
      $button12_icon_1_2,
      $button12_icon_1_3,
      $button12_icon_2_0,
      $button12_icon_2_1,
      $button12_icon_2_2,
      $button12_icon_2_3
    ]      
    

          
#-------------------------------------------
# Binary sensor
#-------------------------------------------
binary_sensor:
#-------------------------------------------
# 0 Ряд
#-------------------------------------------
  - platform: homeassistant
    name: bin_button12_icon_0_0
    entity_id: $button12_entity_0_0
    publish_initial_state: true
    #internal: true
    on_state:
      then:
        lvgl.widget.update:
          id: b_button12_0_0
          state:
            checked: !lambda return x;
    on_press:
      lvgl.widget.update:
        id: w_button12_0_0
        text_color: 0xFFFF00
    on_release:
      lvgl.widget.update:
        id: w_button12_0_0
        text_color: 0xB6B6B6
####################################
  - platform: homeassistant
    name: bin_button12_icon_0_1
    entity_id: $button12_entity_0_1
    publish_initial_state: true
    #internal: true
    on_state:
      then:
        lvgl.widget.update:
          id: b_button12_0_1
          state:
            checked: !lambda return x;
    on_press:
      lvgl.widget.update:
        id: w_button12_0_1
        text_color: 0xFFFF00
    on_release:
      lvgl.widget.update:
        id: w_button12_0_1
        text_color: 0xB6B6B6
####################################
  - platform: homeassistant
    name: bin_button12_icon_0_2
    entity_id: $button12_entity_0_2
    publish_initial_state: true
    #internal: true
    on_state:
      then:
        lvgl.widget.update:
          id: b_button12_0_2
          state:
            checked: !lambda return x;
    on_press:
      lvgl.widget.update:
        id: w_button12_0_2
        text_color: 0xFFFF00
    on_release:
      lvgl.widget.update:
        id: w_button12_0_2
        text_color: 0xB6B6B6
####################################
  - platform: homeassistant
    name: bin_button12_icon_0_3
    entity_id: $button12_entity_0_3
    publish_initial_state: true
    #internal: true
    on_state:
      then:
        lvgl.widget.update:
          id: b_button12_0_3
          state:
            checked: !lambda return x;
    on_press:
      lvgl.widget.update:
        id: w_button12_0_3
        text_color: 0xFFFF00
    on_release:
      lvgl.widget.update:
        id: w_button12_0_3
        text_color: 0xB6B6B6


#-------------------------------------------
# 1 Ряд
#-------------------------------------------
  - platform: homeassistant
    name: bin_button12_icon_1_0
    entity_id: $button12_entity_1_0
    publish_initial_state: true
    #internal: true
    on_state:
      then:
        lvgl.widget.update:
          id: b_button12_1_0
          state:
            checked: !lambda return x;
    on_press:
      lvgl.widget.update:
        id: w_button12_1_0
        text_color: 0xFFFF00
    on_release:
      lvgl.widget.update:
        id: w_button12_1_0
        text_color: 0xB6B6B6
####################################
  - platform: homeassistant
    name: bin_button12_icon_1_1
    entity_id: $button12_entity_1_1
    publish_initial_state: true
    #internal: true
    on_state:
      then:
        lvgl.widget.update:
          id: b_button12_1_1
          state:
            checked: !lambda return x;
    on_press:
      lvgl.widget.update:
        id: w_button12_1_1
        text_color: 0xFFFF00
    on_release:
      lvgl.widget.update:
        id: w_button12_1_1
        text_color: 0xB6B6B6
####################################
  - platform: homeassistant
    name: bin_button12_icon_1_2
    entity_id: $button12_entity_1_2
    publish_initial_state: true
    #internal: true
    on_state:
      then:
        lvgl.widget.update:
          id: b_button12_1_2
          state:
            checked: !lambda return x;
    on_press:
      lvgl.widget.update:
        id: w_button12_1_2
        text_color: 0xFFFF00
    on_release:
      lvgl.widget.update:
        id: w_button12_1_2
        text_color: 0xB6B6B6
####################################
  - platform: homeassistant
    name: bin_button12_icon_1_3
    entity_id: $button12_entity_1_3
    publish_initial_state: true
    #internal: true
    on_state:
      then:
        lvgl.widget.update:
          id: b_button12_1_3
          state:
            checked: !lambda return x;
    on_press:
      lvgl.widget.update:
        id: w_button12_1_3
        text_color: 0xFFFF00
    on_release:
      lvgl.widget.update:
        id: w_button12_1_3
        text_color: 0xB6B6B6

#-------------------------------------------
# 2 Ряд
#-------------------------------------------
  - platform: homeassistant
    name: bin_button12_icon_2_0
    entity_id: $button12_entity_2_0
    publish_initial_state: true
    #internal: true
    on_state:
      then:
        lvgl.widget.update:
          id: b_button12_2_0
          state:
            checked: !lambda return x;
    on_press:
      lvgl.widget.update:
        id: w_button12_2_0
        text_color: 0xFFFF00
    on_release:
      lvgl.widget.update:
        id: w_button12_2_0
        text_color: 0xB6B6B6
####################################
  - platform: homeassistant
    name: bin_button12_icon_2_1
    entity_id: $button12_entity_2_1
    publish_initial_state: true
    #internal: true
    on_state:
      then:
        lvgl.widget.update:
          id: b_button12_2_1
          state:
            checked: !lambda return x;
    on_press:
      lvgl.widget.update:
        id: w_button12_2_1
        text_color: 0xFFFF00
    on_release:
      lvgl.widget.update:
        id: w_button12_2_1
        text_color: 0xB6B6B6
####################################
  - platform: homeassistant
    name: bin_button12_icon_2_2
    entity_id: $button12_entity_2_2
    publish_initial_state: true
    #internal: true
    on_state:
      then:
        lvgl.widget.update:
          id: b_button12_2_2
          state:
            checked: !lambda return x;
    on_press:
      lvgl.widget.update:
        id: w_button12_2_2
        text_color: 0xFFFF00
    on_release:
      lvgl.widget.update:
        id: w_button12_2_2
        text_color: 0xB6B6B6
####################################
  - platform: homeassistant
    name: bin_button12_icon_2_3
    entity_id: $button12_entity_2_3
    publish_initial_state: true
    #internal: true
    on_state:
      then:
        lvgl.widget.update:
          id: b_button12_2_3
          state:
            checked: !lambda return x;
    on_press:
      lvgl.widget.update:
        id: w_button12_2_3
        text_color: 0xFFFF00
    on_release:
      lvgl.widget.update:
        id: w_button12_2_3
        text_color: 0xB6B6B6






#-------------------------------------------
# LVGL
#-------------------------------------------
lvgl:
  pages:
    - id: button12_page     
      width: 100%
      bg_color: 0x000000
      bg_opa: cover
      widgets:
        - image:
            align: CENTER
            src: $background_button12
        - obj:
            bg_opa: TRANSP
            border_opa: TRANSP
            width: 480
            height: 130
            align: CENTER
            x: 0
            y: 0
            layout:
              pad_row: 20
              pad_column: 30
              type: GRID
              grid_columns: [FR(1), FR(1), FR(1), FR(1)]
              grid_rows: [FR(1)]
            widgets:
            ########################
              - button:
                  checkable: true
                  id: b_button12_0_0
                  grid_cell_row_pos: 0
                  grid_cell_column_pos: 0
                  bg_opa: 35%
                  widgets:
                    - label:
                        text_font: button12_48
                        align: center
                        text: $button12_icon_0_0
                        id: w_button12_0_0
                  on_click:
                    homeassistant.service:
                      service: light.toggle
                      data:
                        entity_id: $button12_entity_0_0        
                    
              - button:
                  checkable: true
                  id: b_button12_0_1
                  grid_cell_row_pos: 0
                  grid_cell_column_pos: 1
                  bg_opa: 35%
                  widgets:
                    - label:
                        text_font: button12_48
                        align: center
                        text: $button12_icon_0_1
                        id: w_button12_0_1
                  on_click:
                    homeassistant.service:
                      service: light.toggle
                      data:
                        entity_id: $button12_entity_0_1   
            
              - button:
                  checkable: true
                  id: b_button12_0_2
                  grid_cell_row_pos: 0
                  grid_cell_column_pos: 2
                  bg_opa: 35%
                  widgets:
                    - label:
                        text_font: button12_48
                        align: center
                        text: $button12_icon_0_2
                        id: w_button12_0_2
                  on_click:
                    homeassistant.service:
                      service: light.toggle
                      data:
                        entity_id: $button12_entity_0_2  
            
              - button:
                  checkable: true
                  id: b_button12_0_3
                  grid_cell_row_pos: 0
                  grid_cell_column_pos: 3
                  bg_opa: 35%
                  widgets:
                    - label:
                        text_font: button12_48
                        align: center
                        text: $button12_icon_0_3
                        id: w_button12_0_3
                  on_click:
                    homeassistant.service:
                      service: light.toggle
                      data:
                        entity_id: $button12_entity_0_3  
                        
                        
########################################################################################                        
        - obj:
            bg_opa: TRANSP
            border_opa: TRANSP
            width: 480
            height: 260
            align: CENTER
            x: 0
            y: 130
            layout:
              pad_row: 20
              pad_column: 30
              type: GRID
              grid_columns: [FR(1), FR(1), FR(1), FR(1)]
              grid_rows: [FR(1)]
            widgets:
            ########################
              - button:
                  checkable: true
                  id: b_button12_1_0
                  grid_cell_row_pos: 0
                  grid_cell_column_pos: 1
                  bg_opa: 35%
                  widgets:
                    - label:
                        text_font: button12_48
                        align: center
                        text: $button12_icon_1_0
                        id: w_button12_1_0
                  on_click:
                    homeassistant.service:
                      service: light.toggle
                      data:
                        entity_id: $button12_entity_1_0        
                    
              - button:
                  checkable: true
                  id: b_button12_1_1
                  grid_cell_row_pos: 1
                  grid_cell_column_pos: 1
                  bg_opa: 35%
                  widgets:
                    - label:
                        text_font: button12_48
                        align: center
                        text: $button12_icon_1_1
                        id: w_button12_1_1
                  on_click:
                    homeassistant.service:
                      service: light.toggle
                      data:
                        entity_id: $button12_entity_1_1   
            
              - button:
                  checkable: true
                  id: b_button12_1_2
                  grid_cell_row_pos: 1
                  grid_cell_column_pos: 2
                  bg_opa: 35%
                  widgets:
                    - label:
                        text_font: button12_48
                        align: center
                        text: $button12_icon_1_2
                        id: w_button12_1_2
                  on_click:
                    homeassistant.service:
                      service: light.toggle
                      data:
                        entity_id: $button12_entity_1_2  
            
              - button:
                  checkable: true
                  id: b_button12_1_3
                  grid_cell_row_pos: 1
                  grid_cell_column_pos: 3
                  bg_opa: 35%
                  widgets:
                    - label:
                        text_font: button12_48
                        align: center
                        text: $button12_icon_1_3
                        id: w_button12_1_3
                  on_click:
                    homeassistant.service:
                      service: light.toggle
                      data:
                        entity_id: $button12_entity_1_3     
                        
########################################################################################             
        - obj:
            bg_opa: TRANSP
            border_opa: TRANSP
            width: 480
            height: 130
            align: CENTER
            x: 0
            y: 390
            layout:
              pad_row: 20
              pad_column: 30
              type: GRID
              grid_columns: [FR(1), FR(1), FR(1), FR(1)]
              grid_rows: [FR(1)]
            widgets:
                        
            ########################
              - button:
                  checkable: true
                  id: b_button12_2_0
                  grid_cell_row_pos: 2
                  grid_cell_column_pos: 0
                  bg_opa: 35%
                  widgets:
                    - label:
                        text_font: button12_48
                        align: center
                        text: $button12_icon_2_0
                        id: w_button12_2_0
                  on_click:
                    homeassistant.service:
                      service: light.toggle
                      data:
                        entity_id: $button12_entity_2_0        
                    
              - button:
                  checkable: true
                  id: b_button12_2_1
                  grid_cell_row_pos: 2
                  grid_cell_column_pos: 1
                  bg_opa: 35%
                  widgets:
                    - label:
                        text_font: button12_48
                        align: center
                        text: $button12_icon_2_1
                        id: w_button12_2_1
                  on_click:
                    homeassistant.service:
                      service: light.toggle
                      data:
                        entity_id: $button12_entity_2_1   
            
              - button:
                  checkable: true
                  id: b_button12_2_2
                  grid_cell_row_pos: 2
                  grid_cell_column_pos: 2
                  bg_opa: 35%
                  widgets:
                    - label:
                        text_font: button12_48
                        align: center
                        text: $button12_icon_2_2
                        id: w_button12_2_2
                  on_click:
                    homeassistant.service:
                      service: light.toggle
                      data:
                        entity_id: $button12_entity_2_2  
            
              - button:
                  checkable: true
                  id: b_button12_2_3
                  grid_cell_row_pos: 2
                  grid_cell_column_pos: 3
                  bg_opa: 35%
                  widgets:
                    - label:
                        text_font: button12_48
                        align: center
                        text: $button12_icon_2_3
                        id: w_button12_2_3
                  on_click:
                    homeassistant.service:
                      service: light.toggle
                      data:
                        entity_id: $button12_entity_2_3  
            
            

            
            

            
            
            
 