#########################
#           #           #
#           #           #
#   0_0     #   0_1     #
#           #           #
#########################
#     #     #     #     #
# 1_0 # 1_1 # 1_2 # 1_3 #
#     #     #     #     #
#########################
#     #     #     #     #
# 2_0 # 2_1 # 2_2 # 2_3 #
#     #     #     #     #
#########################

font:
  - file: 'font/materialdesignicons-webfont.ttf' # http://materialdesignicons.com/cdn/7.4.47/ 
    id: button10_48
    size: 48
    bpp: 4
    glyphs: [
      $button10_icon_1_0,
      $button10_icon_1_1,
      $button10_icon_1_2,
      $button10_icon_1_3,
      $button10_icon_2_0,
      $button10_icon_2_1,
      $button10_icon_2_2,
      $button10_icon_2_3
    ]      
  - file: 'font/materialdesignicons-webfont.ttf' # http://materialdesignicons.com/cdn/7.4.47/ 
    id: button10_130
    size: 130
    bpp: 4
    glyphs: [
      $button10_icon_0_0,
      $button10_icon_0_1
      ] 
  
script:
  - id: time_update_button10
    then:
      - lvgl.label.update: 
          id: display_time_button10
          text: !lambda |-
            static char time_buf[17];
            auto now = id(sntp_time).now();            
            snprintf(time_buf, sizeof(time_buf), "%02d:%02d", now.hour, now.minute);
            return time_buf; 
      - lvgl.label.update:
          id: display_date_button10
          text: !lambda |-
            static char time_buf[17];
            auto now = id(sntp_time).now();            
            snprintf(time_buf, sizeof(time_buf), "%02d.%02d.%02d", now.day_of_month, now.month, now.year-2000);
            return time_buf; 

time:
  - id: !extend sntp_time
    on_time_sync:
      - script.execute: time_update_button10
    on_time:
      - minutes: '*'
        seconds: 0
        then:
          - script.execute: time_update_button10
          
#-------------------------------------------
# Binary sensor
#-------------------------------------------
binary_sensor:
#-------------------------------------------
# 0 Ряд
#-------------------------------------------
  - platform: homeassistant
    name: bin_button10_icon_0_0
    entity_id: $button10_entity_0_0
    publish_initial_state: true
    #internal: true
    on_state:
      then:
        lvgl.widget.update:
          id: b_button10_0_0
          state:
            checked: !lambda return x;
    on_press:
      lvgl.widget.update:
        id: w_button10_0_0
        text_color: 0xFFFF00
    on_release:
      lvgl.widget.update:
        id: w_button10_0_0
        text_color: 0xB6B6B6
####################################
  - platform: homeassistant
    name: bin_button10_icon_0_1
    entity_id: $button10_entity_0_1
    publish_initial_state: true
    #internal: true
    on_state:
      then:
        lvgl.widget.update:
          id: b_button10_0_1
          state:
            checked: !lambda return x;
    on_press:
      lvgl.widget.update:
        id: w_button10_0_1
        text_color: 0xFFFF00
    on_release:
      lvgl.widget.update:
        id: w_button10_0_1
        text_color: 0xB6B6B6



#-------------------------------------------
# 1 Ряд
#-------------------------------------------
  - platform: homeassistant
    name: bin_button10_icon_1_0
    entity_id: $button10_entity_1_0
    publish_initial_state: true
    #internal: true
    on_state:
      then:
        lvgl.widget.update:
          id: b_button10_1_0
          state:
            checked: !lambda return x;
    on_press:
      lvgl.widget.update:
        id: w_button10_1_0
        text_color: 0xFFFF00
    on_release:
      lvgl.widget.update:
        id: w_button10_1_0
        text_color: 0xB6B6B6
####################################
  - platform: homeassistant
    name: bin_button10_icon_1_1
    entity_id: $button10_entity_1_1
    publish_initial_state: true
    #internal: true
    on_state:
      then:
        lvgl.widget.update:
          id: b_button10_1_1
          state:
            checked: !lambda return x;
    on_press:
      lvgl.widget.update:
        id: w_button10_1_1
        text_color: 0xFFFF00
    on_release:
      lvgl.widget.update:
        id: w_button10_1_1
        text_color: 0xB6B6B6
####################################
  - platform: homeassistant
    name: bin_button10_icon_1_2
    entity_id: $button10_entity_1_2
    publish_initial_state: true
    #internal: true
    on_state:
      then:
        lvgl.widget.update:
          id: b_button10_1_2
          state:
            checked: !lambda return x;
    on_press:
      lvgl.widget.update:
        id: w_button10_1_2
        text_color: 0xFFFF00
    on_release:
      lvgl.widget.update:
        id: w_button10_1_2
        text_color: 0xB6B6B6
####################################
  - platform: homeassistant
    name: bin_button10_icon_1_3
    entity_id: $button10_entity_1_3
    publish_initial_state: true
    #internal: true
    on_state:
      then:
        lvgl.widget.update:
          id: b_button10_1_3
          state:
            checked: !lambda return x;
    on_press:
      lvgl.widget.update:
        id: w_button10_1_3
        text_color: 0xFFFF00
    on_release:
      lvgl.widget.update:
        id: w_button10_1_3
        text_color: 0xB6B6B6

#-------------------------------------------
# 2 Ряд
#-------------------------------------------
  - platform: homeassistant
    name: bin_button10_icon_2_0
    entity_id: $button10_entity_2_0
    publish_initial_state: true
    #internal: true
    on_state:
      then:
        lvgl.widget.update:
          id: b_button10_2_0
          state:
            checked: !lambda return x;
    on_press:
      lvgl.widget.update:
        id: w_button10_2_0
        text_color: 0xFFFF00
    on_release:
      lvgl.widget.update:
        id: w_button10_2_0
        text_color: 0xB6B6B6
####################################
  - platform: homeassistant
    name: bin_button10_icon_2_1
    entity_id: $button10_entity_2_1
    publish_initial_state: true
    #internal: true
    on_state:
      then:
        lvgl.widget.update:
          id: b_button10_2_1
          state:
            checked: !lambda return x;
    on_press:
      lvgl.widget.update:
        id: w_button10_2_1
        text_color: 0xFFFF00
    on_release:
      lvgl.widget.update:
        id: w_button10_2_1
        text_color: 0xB6B6B6
####################################
  - platform: homeassistant
    name: bin_button10_icon_2_2
    entity_id: $button10_entity_2_2
    publish_initial_state: true
    #internal: true
    on_state:
      then:
        lvgl.widget.update:
          id: b_button10_2_2
          state:
            checked: !lambda return x;
    on_press:
      lvgl.widget.update:
        id: w_button10_2_2
        text_color: 0xFFFF00
    on_release:
      lvgl.widget.update:
        id: w_button10_2_2
        text_color: 0xB6B6B6
####################################
  - platform: homeassistant
    name: bin_button10_icon_2_3
    entity_id: $button10_entity_2_3
    publish_initial_state: true
    #internal: true
    on_state:
      then:
        lvgl.widget.update:
          id: b_button10_2_3
          state:
            checked: !lambda return x;
    on_press:
      lvgl.widget.update:
        id: w_button10_2_3
        text_color: 0xFFFF00
    on_release:
      lvgl.widget.update:
        id: w_button10_2_3
        text_color: 0xB6B6B6





#-------------------------------------------
# LVGL
#-------------------------------------------
lvgl:
  pages:
    - id: button10_page     
      width: 100%
      bg_color: 0x000000
      bg_opa: cover
      widgets:
        - image:
            align: CENTER
            src: $background_button10
        - obj:
            bg_opa: TRANSP
            border_opa: TRANSP
            width: 480
            height: 460
            align: TOP_LEFT
            x: 0
            y: 0
            layout:
              pad_row: 10
              pad_column: 10
              type: GRID
              grid_columns: [FR(1), FR(1), FR(1), FR(1)]
              grid_rows: [FR(1), FR(1), FR(1), FR(1)]
            widgets:
            ########################
              - button:
                  checkable: $button10_checkable_0_0
                  id: b_button10_0_0
                  grid_cell_row_pos: 0 #Позиция ряд
                  grid_cell_column_pos: 0 #Позиция колонка
                  grid_cell_x_align: STRETCH
                  grid_cell_y_align: STRETCH
                  grid_cell_row_span: 2 #Занять ячеек в ряде
                  grid_cell_column_span: 2 #Занять ячеек в колонке
                  bg_opa: 35%
                  widgets:
                    - label:
                        text_font: button10_130
                        align: center
                        text: $button10_icon_0_0
                        id: w_button10_0_0
                    - label:
                        text_font: SEG36
                        id: display_time_button10
                        align: top_mid
                        text: "--:--"
                        long_mode: dot
                    - label:
                        text_font: roboto36
                        align: bottom_mid
                        text: $button10_text_0_0
                        long_mode: dot  
                  on_click:
                    - homeassistant.action:
                        action: $button10_action_0_0
                        data:
                          entity_id: $button10_entity_0_0

              - button:
                  checkable: $button10_checkable_0_1
                  id: b_button10_0_1
                  grid_cell_row_pos: 0 #Позиция ряд
                  grid_cell_column_pos: 2 #Позиция колонка
                  grid_cell_x_align: STRETCH
                  grid_cell_y_align: STRETCH
                  grid_cell_row_span: 2 #Занять ячеек в ряде
                  grid_cell_column_span: 2 #Занять ячеек в колонке
                  bg_opa: 35%
                  widgets:
                    - label:
                        text_font: button10_130
                        align: center
                        text: $button10_icon_0_1
                        id: w_button10_0_1
                    - label:
                        text_font: SEG36
                        id: display_date_button10
                        align: top_mid
                        text: "--.--.--"
                        long_mode: dot
                    - label:
                        text_font: roboto36
                        align: bottom_mid
                        text: $button10_text_0_1
                        long_mode: dot  
                  on_click:
                    - homeassistant.action:
                        action: $button10_action_0_1
                        data:
                          entity_id: $button10_entity_0_1
            

     
            ########################
              - button:
                  checkable: $button10_checkable_1_0
                  id: b_button10_1_0
                  grid_cell_row_pos: 2 #Позиция ряд
                  grid_cell_column_pos: 0 #Позиция колонка
                  grid_cell_x_align: STRETCH
                  grid_cell_y_align: STRETCH
                  grid_cell_row_span: 1 #Занять ячеек в ряде
                  grid_cell_column_span: 1 #Занять ячеек в колонке
                  bg_opa: 35%
                  widgets:
                    - label:
                        text_font: button10_48
                        align: center
                        text: $button10_icon_1_0
                        id: w_button10_1_0
                  on_click:
                    homeassistant.action:
                      action: $button10_action_1_0
                      data:
                        entity_id: $button10_entity_1_0        
                    
              - button:
                  checkable: $button10_checkable_1_1
                  id: b_button10_1_1
                  grid_cell_row_pos: 2 #Позиция ряд
                  grid_cell_column_pos: 1 #Позиция колонка
                  grid_cell_x_align: STRETCH
                  grid_cell_y_align: STRETCH
                  grid_cell_row_span: 1 #Занять ячеек в ряде
                  grid_cell_column_span: 1 #Занять ячеек в колонке
                  bg_opa: 35%
                  widgets:
                    - label:
                        text_font: button10_48
                        align: center
                        text: $button10_icon_1_1
                        id: w_button10_1_1
                  on_click:
                    homeassistant.action:
                      action: $button10_action_1_1
                      data:
                        entity_id: $button10_entity_1_1   
            
              - button:
                  checkable: $button10_checkable_1_2
                  id: b_button10_1_2
                  grid_cell_row_pos: 2 #Позиция ряд
                  grid_cell_column_pos: 2 #Позиция колонка
                  grid_cell_x_align: STRETCH
                  grid_cell_y_align: STRETCH
                  grid_cell_row_span: 1 #Занять ячеек в ряде
                  grid_cell_column_span: 1 #Занять ячеек в колонке
                  bg_opa: 35%
                  widgets:
                    - label:
                        text_font: button10_48
                        align: center
                        text: $button10_icon_1_2
                        id: w_button10_1_2
                  on_click:
                    homeassistant.action:
                      action: $button10_action_1_2
                      data:
                        entity_id: $button10_entity_1_2  
            
              - button:
                  checkable: $button10_checkable_1_3
                  id: b_button10_1_3
                  grid_cell_row_pos: 2 #Позиция ряд
                  grid_cell_column_pos: 3 #Позиция колонка
                  grid_cell_x_align: STRETCH
                  grid_cell_y_align: STRETCH
                  grid_cell_row_span: 1 #Занять ячеек в ряде
                  grid_cell_column_span: 1 #Занять ячеек в колонке
                  bg_opa: 35%
                  widgets:
                    - label:
                        text_font: button10_48
                        align: center
                        text: $button10_icon_1_3
                        id: w_button10_1_3
                  on_click:
                    homeassistant.action:
                      action: $button10_action_1_3
                      data:
                        entity_id: $button10_entity_1_3     
                        
            ########################
              - button:
                  checkable: $button10_checkable_2_0
                  id: b_button10_2_0
                  grid_cell_row_pos: 3 #Позиция ряд
                  grid_cell_column_pos: 0 #Позиция колонка
                  grid_cell_x_align: STRETCH
                  grid_cell_y_align: STRETCH
                  grid_cell_row_span: 1 #Занять ячеек в ряде
                  grid_cell_column_span: 1 #Занять ячеек в колонке
                  bg_opa: 35%
                  widgets:
                    - label:
                        text_font: button10_48
                        align: center
                        text: $button10_icon_2_0
                        id: w_button10_2_0
                  on_click:
                    homeassistant.action:
                      action: $button10_action_2_0
                      data:
                        entity_id: $button10_entity_2_0        
                    
              - button:
                  checkable: $button10_checkable_2_1
                  id: b_button10_2_1
                  grid_cell_row_pos: 3 #Позиция ряд
                  grid_cell_column_pos: 1 #Позиция колонка
                  grid_cell_x_align: STRETCH
                  grid_cell_y_align: STRETCH
                  grid_cell_row_span: 1 #Занять ячеек в ряде
                  grid_cell_column_span: 1 #Занять ячеек в колонке
                  bg_opa: 35%
                  widgets:
                    - label:
                        text_font: button10_48
                        align: center
                        text: $button10_icon_2_1
                        id: w_button10_2_1
                  on_click:
                    homeassistant.action:
                      action: $button10_action_2_1
                      data:
                        entity_id: $button10_entity_2_1   
            
              - button:
                  checkable: $button10_checkable_2_2
                  id: b_button10_2_2
                  grid_cell_row_pos: 3 #Позиция ряд
                  grid_cell_column_pos: 2 #Позиция колонка
                  grid_cell_x_align: STRETCH
                  grid_cell_y_align: STRETCH
                  grid_cell_row_span: 1 #Занять ячеек в ряде
                  grid_cell_column_span: 1 #Занять ячеек в колонке
                  bg_opa: 35%
                  widgets:
                    - label:
                        text_font: button10_48
                        align: center
                        text: $button10_icon_2_2
                        id: w_button10_2_2
                  on_click:
                    homeassistant.action:
                      action: $button10_action_2_2
                      data:
                        entity_id: $button10_entity_2_2  
            
              - button:
                  checkable: $button10_checkable_2_3
                  id: b_button10_2_3
                  grid_cell_row_pos: 3 #Позиция ряд
                  grid_cell_column_pos: 3 #Позиция колонка
                  grid_cell_x_align: STRETCH
                  grid_cell_y_align: STRETCH
                  grid_cell_row_span: 1 #Занять ячеек в ряде
                  grid_cell_column_span: 1 #Занять ячеек в колонке
                  bg_opa: 35%
                  widgets:
                    - label:
                        text_font: button10_48
                        align: center
                        text: $button10_icon_2_3
                        id: w_button10_2_3
                  on_click:
                    homeassistant.action:
                      action: $button10_action_2_3
                      data:
                        entity_id: $button10_entity_2_3    