#############################################################################
#----Страничка CO2 ----------------------------------------------------------
#############################################################################
# Add yaml and copy file esphome/packages/
#packages:
#  co2: !include
#    file: packages/display/co2.yaml
#    vars:
#      sensor_co2: sensor.holl_clock_co2
# 
#############################################################################


substitutions:
  co2_icon: "\U000F07E4" # mdi:molecule-co2
font:
  - file: 'font/materialdesignicons-webfont.ttf' # http://materialdesignicons.com/cdn/7.4.47/ 
    id: co2_36
    size: 48
    bpp: 4
    glyphs: [
      $co2_icon
    ]  
#-------------------------------------------
# IMAGE
#-------------------------------------------
#image:
#  - file: "picture/co2.png"
 #   id: sun_co2
 #   resize: 60x60
 #   type: RGB565 
#-------------------------------------------
# SENSOR
#-------------------------------------------    
sensor:
  - platform: homeassistant
    id: co2
    entity_id: $sensor_co2
    on_value:
      then:
        - lvgl.label.update:
            id: co2_index_text
            text: 
              format: " %.0f"
              args: ["id(co2).state"]

        - lvgl.indicator.update:
            id: co2_meter
            value: !lambda |- 
              return x;
        - lambda: |-
            uint16_t vco2= (id(co2).state);
            switch (vco2) {
              case 0 ... 600: return id(co2_class).publish_state("Отлично");
              case 601 ... 1000: return id(co2_class).publish_state("Хорошо");
              case 1001 ... 1500: return id(co2_class).publish_state("Слегка загрязненный");
              case 1501 ... 2000: return id(co2_class).publish_state("Загрязненный");
              case 2001 ... 7000: return id(co2_class).publish_state("Сильно загрязненный");
              default: return id(co2_class).publish_state("n/a");
            }
              
################################################################
        - lvgl.label.update:
            id: display_co2
            text: 
              format: "$molecule_co2 %.0f ppm"
              args: ["id(co2).state"]
            text_color: !lambda |-
              uint16_t vco2 = (id(co2).state);
              switch (vco2) {
                case 0 ... 600: return lv_color_hex(0x00ff00);
                case 601 ... 1000: return lv_color_hex(0x80FF95);
                case 1001 ... 1500: return lv_color_hex(0xe7c12c);
                case 1501 ... 2000: return lv_color_hex(0xf07c40);
                case 2001 ... 7000: return lv_color_hex(0xff0000);
                default: return lv_color_hex(0x333333);
              }    
################################################################
#-------------------------------------------
# TEXT SENSOR
#-------------------------------------------
text_sensor:
  - platform: template
    id: co2_class
    on_value:
      then:
         - lvgl.label.update:
            id: display_co2_class
            text: !lambda |- 
              return x; 
              
#-------------------------------------------
# LVGL
#-------------------------------------------
lvgl:
  pages:
################################################################
# Добавляем на weather co2
    - id: !extend weather
      widgets:  
        - button:
            y: 160
            x: 0
            align: LEFT_MID
            bg_opa: TRANSP
            shadow_opa: TRANSP
            width: 180
            height: 40
            widgets:  
              - label:
                  align: LEFT_MID
                  id: display_co2
                  text: --- ppm
                  text_font: weather24
                  text_color: 0x808080
            on_press:
              lvgl.page.show: co2_page  
              
# Вывод на экран 
    - id: co2_page
      #width: 100%
      bg_color: 0x000000
      #opa: cover
      scrollbar_mode: "OFF"
      scrollable: false
      widgets:
        # Зеленый
        - line:
            points:
              - 284, 304
              - -10, 500
            line_width: 150
            line_color: 0x00ff00
            line_rounded: false 
        - line:
            points:
              - 220, 200
              - -30, 365
            line_width: 100
            line_color: 0x00ff00
            line_rounded: false
            
        # Желтый
        - line:
            points:
              - 220, 185
              - -30, 270
            line_width: 110
            line_color: 0xe7c12c
            line_rounded: false 
            
        # Оранжевый
        - line:
            points:
              - 90, 220
              - 120, 0
            line_width: 250
            line_color: 0xffa500
            line_rounded: false    
            
        # Красный
        - line:
            points:
              - 170, 110
              - 480, -80
            line_width: 300
            line_color: 0xF50F34
            line_rounded: false 
            
         # Фиолетовый
        - line:
            points:
              - 310, 240
              - 310, 0
            line_width: 140
            line_color: 0xA63DC2
            line_rounded: false 
            
         # Фиолетовый
        - line:
            points:
              - 330, 295
              - 482, 0 #+5 -5
            line_width: 220
            line_color: 0xA63DC2
            line_rounded: false 
         # Фиолетовый
        - line:
            points:
              - 360, 220
              - 390, 480
            line_color: 0xA63DC2
            line_width: 240
            line_rounded: false
      
  
         # Белый
        - line:
            points:
              - 105, 585
              - 345, 345
            align: TOP_left
            line_width: 300
            line_color: 0xFFFFFF
            line_rounded: false 
# Шкала
        - meter:
            bg_opa: 0%
            opa: 100%
            #bg_color: color_blue
            shadow_color: color_blue
            shadow_spread: 2
            shadow_width: 25
            shadow_opa: 100%
            border_width: 15
            width: 300
            height: 300
            align: center
            scales:
              - ticks: 
                  count: 101
                  width: 2
                  length: 10
                  color: 0x000000
                  major:
                    stride: 10
                    width: 3
                    length: 20
                    color: 0x000000
                    label_gap: 10
                angle_range: 270
                rotation: 135
                range_from: 0
                range_to: 100
# Индикатор
        - meter:
            width: 200
            height: 200
            align: center
            scales:
              - indicators:
                  - line:
                      id: co2_meter
                      width: 4
                      color: 0xFF0000
                      r_mod: -15
                      value: 0
                angle_range: 270
                rotation: 135
                range_from: 0
                range_to: 5000
                ticks: 
                  count: 101
                  width: 0
                  length: 0
                  color: 0x000000
                  major:
                    stride: 10
                    width: 0
                    length: 0
                    color: 0x000000
                    label_gap: 8
                    
        - led:
           y: 65
           align: CENTER
           color: 808080
           width: 40
           height: 25         
        - label:
            id: co2_index_text
            text: "--"
            text_color: color_violet
            align: CENTER
            y: 65
                  
        - spinner:
            width: 245
            height: 245
            align: center
            spin_time: 0s
            arc_length: 0deg
            arc_width: 3
            arc_color: 0x000000
            indicator:
              arc_width: 3
              arc_color: 0x000000
              

        - label:
            id: display_co2_class
            text_color: color_white
            text: "Качество воздуха"
            text_font: roboto36
            align: TOP_MID 
            y: 50
        - label:
            text: $co2_icon
            text_color: color_black
            text_font: co2_36
            align: BOTTOM_MID
            y: -40
            
     #   - image:
      #      align: CENTER
      #      src: co2
     #       y: 180
      #      bg_color: 0xFFFFFF
        #    bg_image_opa: 100% 
