esphome:
  on_boot:
    - light.turn_on: backlight
    

#-------------------------------------------
# SPI
#-------------------------------------------  
spi:
    clk_pin: GPIO48
    mosi_pin: GPIO47

#-------------------------------------------
# PSRAM
#-------------------------------------------
psram:
  mode: octal
  speed: 80MHz

#-------------------------------------------
# COLORS
#-------------------------------------------          
color:
  - id: color_black
    hex: 0d0d0d
  - id: color_dark_gray
    hex: 333333
  - id: color_gray
    hex: 666666
  - id: color_white
    hex: f2f0eb
  - id: color_red
    hex: ff0000
  - id: color_crimson
    hex: f5075c
  - id: color_blue
    hex: 2fc0ff
  - id: color_yellow
    hex: e7c12c
  - id: color_amber
    hex: f4a900
  - id: color_mint
    hex: 39d19c
  - id: color_green
    hex: 00ff00
  - id: color_orange
    hex: f07c40
  - id: color_deep_orange
    hex: ff6600
  - id: color_violet
    hex: 9670d6
  - id: color_dark_blue
    hex: 4867aa


#-------------------------------------------
# FONT
#-------------------------------------------
font:   
  - file: "gfonts://Roboto"
    id: roboto36
    glyphs: ${characters}
    size: 36
    bpp: 4     

  - file: "gfonts://Roboto"
    id: roboto24
    glyphs: ${characters}
    size: 24
    bpp: 4  

  - file: "font/DSEG7ModernMini-Bold.ttf"
    id: SEG36
    glyphs: ${number_characters}
 #     :.-0123456789
    size: 36

    bpp: 4  
  - file: "gfonts://Roboto"
    id: menu24
    size: 24
    bpp: 4
    extras:
      - file: 'font/materialdesignicons-webfont.ttf' # http://materialdesignicons.com/cdn/7.4.47/ 
        glyphs: [
          "\U000F06A1",
          "\U000F0141",
          "\U000F0142"
        ]
#-------------------------------------------
# switch
#-------------------------------------------
switch:
  - platform: template
    name: Antiburn
    id: switch_antiburn
    icon: mdi:television-shimmer
    optimistic: true
    entity_category: "config"
    turn_on_action:
      - if:
          condition: lvgl.is_paused
          then:
            - lvgl.resume:
            - lvgl.widget.redraw:
            - delay: 1s
      - lvgl.pause:
          show_snow: true
    turn_off_action:
      - if:
          condition: lvgl.is_paused
          then:
            - lvgl.resume:
            - lvgl.widget.redraw:
            - delay: 1s
            - lvgl.pause:
            
#-------------------------------------------
# Outputs
#-------------------------------------------
output:
  - platform: ledc
    pin: GPIO38
    id: GPIO38
    frequency: 150Hz

#-------------------------------------------
# LIGHTS
# value: !lambda return (id(backlight).state)->brightness  *100; 
#-------------------------------------------
light:
  - platform: monochromatic
    output: GPIO38
    name: Backlight
    id: backlight
    icon: mdi:television-ambient-light
    gamma_correct: 1.8

#-------------------------------------------
# Buttons
#-------------------------------------------
button:
  - platform: template
    name: "Next page"
    on_press:
      then:
        lvgl.page.next:   
  - platform: template
    name: "Previous page"
    on_press:
      then:
        lvgl.page.previous:      
        
#-------------------------------------------
# GLOBALS
#-------------------------------------------          
globals:
  - id: lv_timeout
    type: float
    restore_value: yes
    initial_value: '30000'
    
#-------------------------------------------
# SELECT
#-------------------------------------------
select:
  - platform: template
    name: "Rotate Screen"
    id: rotate
    entity_category: config
    options:
     - "0°"      
     - "90°"
     - "180°"
     - "270°"
    initial_option: "180°"
    optimistic: true
    icon: mdi:phone-rotate-landscape
    on_value:
      then:
        - if:
            condition:
              select.is:
                id: rotate
                options: [0°]
            then:
              - lvgl.display.set_rotation: 0
        - if:
            condition:
              select.is:
                id: rotate
                options: [90°]
            then:
              - lvgl.display.set_rotation: 90
        - if:
            condition:
              select.is:
                id: rotate
                options: [180°]
            then:
              - lvgl.display.set_rotation: 180
        - if:
            condition:
              select.is:
                id: rotate
                options: [270°]
            then:
              - lvgl.display.set_rotation: 270
        - lvgl.widget.redraw:

#-------------------------------------------
# TOUCHSCREEN
#-------------------------------------------
touchscreen:
  platform: gt911
  transform:
    mirror_x: false
    mirror_y: true
    swap_xy: false
  id: my_touchscreen
  display: my_display
  update_interval: 50ms
  on_release:
    then:
      - if:
          condition: lvgl.is_paused
          then:
            - lvgl.resume:
            - lvgl.widget.redraw:
      - light.turn_on: backlight

#-------------------------------------------
# DISPLAY
#-------------------------------------------
display:
  - platform: mipi_rgb
    model: GUITION-4848S040
    id: my_display
   # spi_mode: MODE3
    update_interval: never
   # pclk_frequency: 12MHz
    
    
 #-------------------------------------------   
# LVGL
#-------------------------------------------    
lvgl:
  buffer_size: $buffer_lvgl
  displays:
    -  my_display
  touchscreens:
    -  my_touchscreen