#############################################################################
#----Страничка Doorbell------------------------------------
#############################################################################
# Add yaml and copy file esphome/packages/
#packages:
#  doorbell: !include 
#    file: packages/display/door_bell.yaml
#    vars:
#      button_doorbell: binary_sensor.doorbell
#      url_image: "http://192.168.1.10:8123/static/icons/favicon-192x192.png"
#
#############################################################################

http_request:

online_image:
  - url: $url_image
    id: doorbell_image
    format: PNG
    transparency: alpha_channel
    type: RGB565
    resize: 480x480
    on_download_finished:
      - lvgl.image.update:
          id: doorbell_image_widget
          src: doorbell_image
      - lvgl.page.show: doorbell_page
      - light.turn_on: backlight

binary_sensor:
  - platform: homeassistant
    id: doorbell_pressed
    name: "Doorbell Pressed"
    entity_id: $button_doorbell
    on_press:
      - component.update: doorbell_image
button:  
  - platform: template
    name: "Doorbell image"
    on_press:
      - component.update: doorbell_image
lvgl:
  pages:
    - id: doorbell_page
      width: 100%
      bg_color: 0x000000
      bg_opa: cover
      scrollbar_mode: "OFF"
      widgets:
        - image:
            align: CENTER
            src: doorbell_image
            id: doorbell_image_widget
   