#-------------------------------------------
# IMAGE
#-------------------------------------------
image:
  - file: "picture/magnet.png"
    id: magnit
    resize: 50x50
    type: RGB565 
#-------------------------------------------
# SENSOR
#-------------------------------------------    
sensor:
  - platform: homeassistant
    id: geomagnetic
    entity_id: $sensor_geomagnetic
    on_value:
      then:
        - lvgl.label.update:
            id: geomagnetic_text
            text: 
              format: " %.0f "
              args: ["id(geomagnetic).state"]

        - lvgl.indicator.update:
            id: geomagnetic_meter
            value: !lambda |- 
              return x;
        - lambda: |-
            uint8_t vgeomag= (id(geomagnetic).state);
              switch (vgeomag) {
                case 0 ... 4: return id(geomag_class).publish_state("небольшие возмущения");
                case 5: return id(geomag_class).publish_state("слабая буря");
                case 6: return id(geomag_class).publish_state("умеренная буря");
                case 7: return id(geomag_class).publish_state("сильная буря");
                case 8: return id(geomag_class).publish_state("шторм");
                case 9: return id(geomag_class).publish_state("экстремальный шторм");
                default: return id(geomag_class).publish_state("n/a");
              }
#-------------------------------------------
# TEXT SENSOR
#-------------------------------------------
text_sensor:             
  - platform: template
    id: geomag_class
    on_value:
      then:
         - lvgl.label.update:
            id: display_geomag_class
            text: !lambda |- 
              return x;            

#-------------------------------------------
# LVGL
#-------------------------------------------  
lvgl:
  pages:
# Вывод на экран 
    - id: geomag
      #width: 100%
      bg_color: 0x000000
      #opa: cover
      scrollbar_mode: "OFF"
      scrollable: false
      widgets:
        # Зеленый
        - line:
            points:
              - 170, 170
              - -70, 410
            line_width: 200
            line_color: 0x00ff00
            line_rounded: false 
        - line:
            points:
              - 120, 0
              - 120, 240
            line_width: 240
            line_color: 0x00ff00
            line_rounded: false 
        
        # Желтый
        - line:
            points:
              - 310, 240
              - 310, 0
            line_width: 140
            line_color:  0xe7c12c
            line_rounded: false 
            
        # Оранжевый
        - line:
            points:
              - 309, 279
              - 465, -15 
            line_width: 160
            line_color: 0xffa500
            line_rounded: false 
        # Красный
        - line:
            points:
              - 274, 304
              - 519, 154 #-10
            line_width: 140
            line_color: 0xF50F34
            line_rounded: false 
        # Фиолетовый
        - line:
            points:
              - 240, 320
              - 480, 320
            line_color: 0x9412FD
            line_width: 160
            line_rounded: false
        # Темно фиолетовый
        - line:
            points:
              - 196, 304
              - 490, 500
            line_width: 160
            line_color: 0xA63DC2
            line_rounded: false 
        
        - line:
            points:
              - 105, 585
              - 345, 345
            align: TOP_left
            line_width: 300
            line_color: 0x000000
            line_rounded: false 

        - meter:
            bg_opa: 0%
            opa: 100%
            #bg_color: color_blue
            shadow_color: color_blue
            shadow_spread: 2
            shadow_width: 25
            shadow_opa: 100%
            border_width: 15
            width: 300
            height: 300
            align: center
            scales:
              - ticks: 
                  count: 19
                  width: 2
                  length: 10
                  color: 0x000000
                  major:
                    stride: 2
                    width: 3
                    length: 20
                    color: 0x000000
                    label_gap: 10
                angle_range: 270
                rotation: 135
                range_from: 0
                range_to: 9
        - meter:
            width: 200
            height: 200
            align: center
            scales:
              - indicators:
                  - line:
                      id: geomagnetic_meter
                      width: 4
                      color: 0xFF0000
                      r_mod: -15
                      value: 0
                angle_range: 270
                rotation: 135
                range_from: 0
                range_to: 9
                ticks: 
                  count: 10
                  width: 0
                  length: 0
                  color: 0x000000
                  major:
                    stride: 1
                    width: 0
                    length: 0
                    color: 0x000000
                    label_gap: 8
        - led:
           y: 65
           align: CENTER
           color: 808080
           width: 40
           height: 25          
        - label:
           id: geomagnetic_text
           text: "-"
           text_color: color_blue
           align: CENTER
           y: 65
                  
        - spinner:
            width: 245
            height: 245
            align: center
            spin_time: 0s
            arc_length: 0deg
            arc_width: 3
            arc_color: 0x000000
            indicator:
              arc_width: 3
              arc_color: 0x000000
        - label:
            text_color: color_white
            text: Геомагнитная активность
            text_font: roboto36
            align: TOP_MID 
        - label:
            id: display_geomag_class
            text_color: color_white
            text_font: roboto36
            align: TOP_MID 
            y: 50
        - image:
            align: CENTER
            src: magnit
            y: 180
            bg_color: 0xFFFFFF
            bg_image_opa: 100% 
