image:
  - file: "picture/geomag.jpg"
    id: geo_image
    resize: 480x480
    type: RGB565 
  - file: "picture/magnet.png"
    id: magnit
    resize: 50x50
    type: RGB565 
    
sensor:
  - platform: homeassistant
    id: geomagnetic
    entity_id: $sensor_geomagnetic
    on_value:
      then:
        - lvgl.label.update:
            id: geomagnetic_text
            text: 
              format: " %.0f "
              args: ["id(geomagnetic).state"]

        - lvgl.indicator.update:
            id: geomagnetic_meter
            value: !lambda |- 
              return x;
 
lvgl:
  pages:
# Вывод на экран 
    - id: geomag_page
      width: 100%
      bg_color: 0x000000
      bg_opa: cover
      widgets:
        - image:
            align: CENTER
            src: geo_image 
        - image:
            align: CENTER
            src: magnit
            y: 140
            bg_image_opa: 100%  
        - meter:
            height: 150
            width: 150
            x: -5
            y: -5
            border_width: 0
            bg_opa: TRANSP
            align: center
            scales:
              - indicators:
                  - line:
                      id: geomagnetic_meter
                      width: 4
                      color: 0xFF0000
                      r_mod: 20
                      value: 0
                angle_range: 280
                rotation: 130
                range_from: 0
                range_to: 9
                ticks:
                  count: 0
            widgets:
              - label:
                  id: geomagnetic_text
                  text: "--"
                  align: CENTER
                  y: 65
 
            