image:
  - file: "picture/humm.jpg"
    id: humm_image
    resize: 480x480
    type: RGB565 
    
  - file: "picture/humm_Logo1.jpg"
    id: dewpoint
    resize: 100x100
    type: RGB565 

sensor:
  - platform: homeassistant
    id: humidity
    entity_id: $sensor_humidity
    on_value:
      then:
        - lvgl.label.update:
            id: humidity_text
            text: 
              format: " %.0f %%"
              args: ["id(humidity).state"]

        - lvgl.indicator.update:
            id: humidity_meter
            value: !lambda |- 
              return x;
 
lvgl:
  pages:
# Вывод на экран 
    - id: humm_page
      width: 100%
      bg_color: 0x000000
      bg_opa: cover
      widgets:
        - image:
            align: CENTER
            src: humm_image 
        - image:
            align: CENTER
            src: dewpoint
            bg_image_opa: 0%  
            
        - meter:
            height: 150
            width: 150
            x: -5
            y: -5
            border_width: 0
            bg_opa: TRANSP
            align: center
            widgets:
              - label:
                  id: humidity_text
                  text: "-- %"
                  align: CENTER
                  y: 45
            scales:
              - indicators:
                  - line:
                      id: humidity_meter
                      width: 4
                      color: 0xFF0000
                      r_mod: 20
                      value: 0
                angle_range: 280
                rotation: 130
                range_from: 0
                range_to: 100
                ticks:
                  count: 0



          