#-------------------------------------------
# IMAGE
#-------------------------------------------
image:
  - file: "picture/humm_Logo3.jpg"
    id: humm_image
    resize: 60x60
    type: RGB565 
#-------------------------------------------
# SENSOR
#-------------------------------------------    
sensor:
  - platform: homeassistant
    id: humm
    entity_id: $sensor_humidity
    on_value:
      then:
        - lambda: |-
            uint8_t vhumm= (id(humm).state);
              switch (vhumm) {
                case 0 ... 29: return id(humm_class).publish_state("сухой");
                case 30 ... 49: return id(humm_class).publish_state("почти сухой");
                case 50 ... 54: return id(humm_class).publish_state("очень комфортный");
                case 55 ... 59: return id(humm_class).publish_state("комфортный"); 
                case 60 ... 64: return id(humm_class).publish_state("хороший");
                case 65 ... 69: return id(humm_class).publish_state("не комфортный");
                case 70 ... 74: return id(humm_class).publish_state("угнетающий");
                case 75 ... 79: return id(humm_class).publish_state("влажный");
                case 80 ... 100: return id(humm_class).publish_state("очень влажный");
                default: return id(humm_class).publish_state("n/a");
              }
              
        - lvgl.label.update:
            id: humm_index_text
            text: 
              format: " %.0f"
              args: ["id(humm).state"]

        - lvgl.indicator.update:
            id: humm_meter
            value: !lambda |- 
              return x;

#-------------------------------------------
# TEXT SENSOR
#-------------------------------------------
text_sensor: 
  - platform: template
    id: humm_class
    on_value:
      then:
        - lvgl.label.update:
            id: display_humm_class
            text: !lambda |- 
              return x; 
#-------------------------------------------
# LVGL
#-------------------------------------------
lvgl:
  pages:
# Вывод на экран 
    - id: humm_page
      #width: 100%
      bg_color: 0x000000
      #opa: cover
      scrollbar_mode: "OFF"
      scrollable: false
      widgets:
        # Оранжевый
        - line:
            points:
              - 170, 170
              - -70, 410
            line_width: 200
            line_color: 0xffa500 
            line_rounded: false 
        - line:
            points:
              - 120, 0
              - 120, 240
            line_width: 240
            line_color: 0xffa500
            line_rounded: false 
            
        # Желтый
        - line:
            points:
              - 329, 190
              - 0, -35
            line_width: 200
            line_color: 0xe7c12c
            line_rounded: false 

        # Зеленый
        - line:
            points:
              - 310, 240
              - 310, 0
            line_width: 140
            line_color:  0x00FF00
            line_rounded: false 
            
        # Салатовый      
        - line:
            points:
              - 309, 279
              - 385, -15 
            line_width: 160
            line_color: 0xa6e278 
            line_rounded: false 
        
        # Аквамариновый
        - line:
            points:
              - 309, 279
              - 465, -15 
            line_width: 160
            line_color: 0x78dbe2 
            line_rounded: false 
            
        #Голубой
        - line:
            points:
              - 274, 280
              - 480, 0 #-10
            line_width: 90
            line_color: 0x42aaff
            line_rounded: false 
            
        # Синий
        - line:
            points:
              - 274, 280
              - 510, 70 #-10
            line_width: 90
            line_color: 0x0000ff
            line_rounded: false 

        # Фиолетовый
        - line:
            points:
              - 274, 280
              - 519, 154 #-10
            line_width: 90
            line_color: 0xA63DC2 
            line_rounded: false 
            
        # Темно фиолетовый
        - line:
            points:
              - 360, 220
              - 390, 480
            line_color: 0x6e029c
            line_width: 240
            line_rounded: false
            
         # Белый
        - line:
            points:
              - 105, 585
              - 345, 345
            align: TOP_left
            line_width: 300
            line_color: 0xFFFFFF
            line_rounded: false 

# Шкала
        - meter:
            bg_opa: 0%
            opa: 100%
            #bg_color: color_blue
            shadow_color: color_blue
            shadow_spread: 2
            shadow_width: 25
            shadow_opa: 100%
            border_width: 15
            width: 300
            height: 300
            align: center
            scales:
              - ticks: 
                  count: 101
                  width: 2
                  length: 10
                  color: 0x000000
                  major:
                    stride: 10
                    width: 3
                    length: 20
                    color: 0x000000
                    label_gap: 10
                angle_range: 270
                rotation: 135
                range_from: 0
                range_to: 100
# Индикатор
        - meter:
            width: 200
            height: 200
            align: center
            scales:
              - indicators:
                  - line:
                      id: humm_meter
                      width: 4
                      color: 0xFF0000
                      r_mod: -15
                      value: 0
                angle_range: 270
                rotation: 135
                range_from: 0
                range_to: 100
                ticks: 
                  count: 101
                  width: 0
                  length: 0
                  color: 0x000000
                  major:
                    stride: 10
                    width: 0
                    length: 0
                    color: 0x000000
                    label_gap: 8
                    
        - led:
           y: 65
           align: CENTER
           color: 808080
           width: 40
           height: 25         
        - label:
            id: humm_index_text
            text: "--"
            text_color: color_violet
            align: CENTER
            y: 65
                  
        - spinner:
            width: 245
            height: 245
            align: center
            spin_time: 0s
            arc_length: 0deg
            arc_width: 3
            arc_color: 0x000000
            indicator:
              arc_width: 3
              arc_color: 0x000000
              
        - label:
            text: "Воздух"
            text_color: color_white
            text_font: roboto36
            align: TOP_MID  
        - label:
            id: display_humm_class
            text_color: color_white
            text_font: roboto36
            align: TOP_MID 
            y: 50
        - label:
            text: "%"
            text_color: color_white
            text_font: weather36
            align: BOTTOM_MID
            y: -40
            
        - image:
            align: CENTER
            src: humm_image
            y: 180
            bg_color: 0xFFFFFF
            bg_image_opa: 100% 
