#############################################################################
#----Страничка влажности на улице -------------------------------------------
#############################################################################
# Add yaml and copy file esphome/packages/
#packages:
#  humm-out: !include 
#    file: packages/display/humm-out.yaml
#    vars:
#      sensor_humidity_out: sensor.iaroslavskaia_humidity
# 
#############################################################################

#-------------------------------------------
# IMAGE
#-------------------------------------------
image:
  - file: "picture/humm_Logo3.jpg"
    id: humm_out_image
    resize: 60x60
    type: RGB565 
#-------------------------------------------
# SENSOR
#-------------------------------------------    
sensor:
  - platform: homeassistant
    id: humm_out
    entity_id: $sensor_humidity_out
    on_value:
      then:
        - lambda: |-
            uint8_t vhumm_out= (id(humm_out).state);
            switch (vhumm_out) {
              case 0 ... 29: return id(humm_out_class).publish_state("сухой");
              case 30 ... 49: return id(humm_out_class).publish_state("почти сухой");
              case 50 ... 54: return id(humm_out_class).publish_state("очень комфортный");
              case 55 ... 59: return id(humm_out_class).publish_state("комфортный"); 
              case 60 ... 64: return id(humm_out_class).publish_state("хороший");
              case 65 ... 69: return id(humm_out_class).publish_state("не комфортный");
              case 70 ... 74: return id(humm_out_class).publish_state("угнетающий");
              case 75 ... 79: return id(humm_out_class).publish_state("влажный");
              case 80 ... 100: return id(humm_out_class).publish_state("очень влажный");
              default: return id(humm_out_class).publish_state("n/a");
            }
              
        - lvgl.label.update:
            id: humm_out_index_text
            text: 
              format: " %.0f"
              args: ["id(humm_out).state"]

        - lvgl.indicator.update:
            id: humm_out_meter
            value: !lambda |- 
              return x;
################################################################
        - lvgl.label.update:
            id: display_hum
            text: 
              format: "%.0f %%"
              args: ["id(humm_out).state"]  
            text_color: !lambda |-
              uint8_t hum_var = (id(humm_out).state);
              switch (hum_var) {
                case 0 ... 30: return lv_color_hex(0x00ff00);
                case 31 ... 50: return lv_color_hex(0xe7c12c);
                case 51 ... 60: return lv_color_hex(0x00ff00);
                case 61 ... 70: return lv_color_hex(0xe7c12c);
                case 71 ... 100: return lv_color_hex(0x2fc0ff);
                default: return lv_color_hex(0x333333);
              }   
################################################################

#-------------------------------------------
# TEXT SENSOR
#-------------------------------------------
text_sensor: 
  - platform: template
    id: humm_out_class
    on_value:
      then:
        - lvgl.label.update:
            id: display_humm_out_class
            text: !lambda |- 
              return x; 
#-------------------------------------------
# LVGL
#-------------------------------------------
lvgl:
  pages:
################################################################
# Добавляем на weather humm_out
    - id: !extend weather
      widgets:  
        - button:
            y: 80
            x: 10
            align: TOP_LEFT
            bg_opa: TRANSP
            shadow_opa: TRANSP
            width: 90
            height: 40
            widgets:  
              - label:
                  align: LEFT_MID
                  id: display_hum
                  text:  --.- %
                  text_font: roboto36
                  text_color: 0x808080
            on_press:
              lvgl.page.show: humm_out_page  
################################################################

# Вывод на экран 
    - id: humm_out_page
      #width: 100%
      bg_color: 0x000000
      #opa: cover
      scrollbar_mode: "OFF"
      scrollable: false
      widgets:
        # Оранжевый
        - line:
            points:
              - 170, 170
              - -70, 410
            line_width: 200
            line_color: 0xffa500 
            line_rounded: false 
        - line:
            points:
              - 120, 0
              - 120, 240
            line_width: 240
            line_color: 0xffa500
            line_rounded: false 
            
        # Желтый
        - line:
            points:
              - 329, 190
              - 0, -35
            line_width: 200
            line_color: 0xe7c12c
            line_rounded: false 

        # Зеленый
        - line:
            points:
              - 310, 240
              - 310, 0
            line_width: 140
            line_color:  0x00FF00
            line_rounded: false 
            
        # Салатовый      
        - line:
            points:
              - 309, 279
              - 385, -15 
            line_width: 160
            line_color: 0xa6e278 
            line_rounded: false 
        
        # Аквамариновый
        - line:
            points:
              - 309, 279
              - 465, -15 
            line_width: 160
            line_color: 0x78dbe2 
            line_rounded: false 
            
        #Голубой
        - line:
            points:
              - 274, 280
              - 480, 0 #-10
            line_width: 90
            line_color: 0x42aaff
            line_rounded: false 
            
        # Синий
        - line:
            points:
              - 274, 280
              - 510, 70 #-10
            line_width: 90
            line_color: 0x0000ff
            line_rounded: false 

        # Фиолетовый
        - line:
            points:
              - 274, 280
              - 519, 154 #-10
            line_width: 90
            line_color: 0xA63DC2 
            line_rounded: false 
            
        # Темно фиолетовый
        - line:
            points:
              - 360, 220
              - 390, 480
            line_color: 0x6e029c
            line_width: 240
            line_rounded: false
            
         # Белый
        - line:
            points:
              - 105, 585
              - 345, 345
            align: TOP_left
            line_width: 300
            line_color: 0xFFFFFF
            line_rounded: false 

# Шкала
        - meter:
            bg_opa: 0%
            opa: 100%
            #bg_color: color_blue
            shadow_color: color_blue
            shadow_spread: 2
            shadow_width: 25
            shadow_opa: 100%
            border_width: 15
            width: 300
            height: 300
            align: center
            scales:
              - ticks: 
                  count: 101
                  width: 2
                  length: 10
                  color: 0x000000
                  major:
                    stride: 10
                    width: 3
                    length: 20
                    color: 0x000000
                    label_gap: 10
                angle_range: 270
                rotation: 135
                range_from: 0
                range_to: 100
# Индикатор
        - meter:
            width: 200
            height: 200
            align: center
            scales:
              - indicators:
                  - line:
                      id: humm_out_meter
                      width: 4
                      color: 0xFF0000
                      r_mod: -15
                      value: 0
                angle_range: 270
                rotation: 135
                range_from: 0
                range_to: 100
                ticks: 
                  count: 101
                  width: 0
                  length: 0
                  color: 0x000000
                  major:
                    stride: 10
                    width: 0
                    length: 0
                    color: 0x000000
                    label_gap: 8
                    
        - led:
           y: 65
           align: CENTER
           color: 808080
           width: 40
           height: 25         
        - label:
            id: humm_out_index_text
            text: "--"
            text_color: color_violet
            align: CENTER
            y: 65
                  
        - spinner:
            width: 245
            height: 245
            align: center
            spin_time: 0s
            arc_length: 0deg
            arc_width: 3
            arc_color: 0x000000
            indicator:
              arc_width: 3
              arc_color: 0x000000
              
        - label:
            text: "Воздух"
            text_color: color_white
            text_font: roboto36
            align: TOP_MID  
        - label:
            id: display_humm_out_class
            text_color: color_white
            text_font: roboto36
            text: " "
            align: TOP_MID 
            y: 50
        - label:
            text: "%"
            text_color: color_white
            text_font: weather36
            align: BOTTOM_MID
            y: -40
            
        - image:
            align: CENTER
            src: humm_out_image
            y: 180
            bg_color: 0xFFFFFF
            bg_image_opa: 100% 



          
