#-------------------------------------------
# IMAGE
#-------------------------------------------
#image:
#  - file: "picture/iaq.png"
 #   id: sun_iaq
 #   resize: 60x60
 #   type: RGB565 
#-------------------------------------------
# SENSOR
#-------------------------------------------    
sensor:
  - platform: homeassistant
    id: iaq
    entity_id: $sensor_iaq
    on_value:
      then:
        - lvgl.label.update:
            id: iaq_index_text
            text: 
              format: " %.0f"
              args: ["id(iaq).state"]

        - lvgl.indicator.update:
            id: iaq_meter
            value: !lambda |- 
              return x;
        - lambda: |-
            uint16_t viaq= (id(iaq).state);
              switch (viaq) {
                case 0 ... 50: return id(iaq_class).publish_state("Отлично");
                case 51 ... 100: return id(iaq_class).publish_state("Хорошо");
                case 101 ... 150: return id(iaq_class).publish_state("Слегка загрязненный");
                case 151 ... 200: return id(iaq_class).publish_state("Умеренно загрязненный");
                case 201 ... 250: return id(iaq_class).publish_state("Слегка загрязненный");
                case 251 ... 300: return id(iaq_class).publish_state("Загрязненный");
                case 301 ... 350: return id(iaq_class).publish_state("Сильно загрязненный");
                case 351 ... 500: return id(iaq_class).publish_state("Черезвычайно загрязненный"); 
                default: return id(iaq_class).publish_state("n/a");
              }
    
#-------------------------------------------
# TEXT SENSOR
#-------------------------------------------
text_sensor:
  - platform: template
    id: iaq_class
    on_value:
      then:
         - lvgl.label.update:
            id: display_iaq_class
            text: !lambda |- 
              return x; 
#-------------------------------------------
# LVGL
#-------------------------------------------
lvgl:
  pages:
# Вывод на экран 
    - id: iaq_page
      #width: 100%
      bg_color: 0x000000
      #opa: cover
      scrollbar_mode: "OFF"
      scrollable: false
      widgets:
        # Зеленый
        - line:
            points:
              - 170, 170
              - -70, 410
            line_width: 200
            line_color: 0x00ff00
            line_rounded: false 
        # Желтый
        - line:
            points:
              - 90, 220
              - 120, 0
            line_width: 250
            line_color:  0xe7c12c
            line_rounded: false  
        # Оранжевый
        - line:
            points:
              - 170, 110
              - 480, -80
            line_width: 300
            line_color: 0xffa500
            line_rounded: false 
            
        # Красный
        - line:
            points:
              - 330, 295
              - 482, 0 #+5 -5
            line_width: 220
            line_color: 0xF50F34
            line_rounded: false 
        # Красный
        - line:
            points:
              - 360, 220
              - 390, 480
            line_color: 0xF50F34
            line_width: 240
            line_rounded: false
      
  
         # Черный
        - line:
            points:
              - 105, 585
              - 345, 345
            align: TOP_left
            line_width: 300
            line_color: 0x000000
            line_rounded: false 
# Шкала
        - meter:
            bg_opa: 0%
            opa: 100%
            #bg_color: color_blue
            shadow_color: color_blue
            shadow_spread: 2
            shadow_width: 25
            shadow_opa: 100%
            border_width: 15
            width: 300
            height: 300
            align: center
            scales:
              - ticks: 
                  count: 101
                  width: 2
                  length: 10
                  color: 0x000000
                  major:
                    stride: 10
                    width: 3
                    length: 20
                    color: 0x000000
                    label_gap: 10
                angle_range: 270
                rotation: 135
                range_from: 0
                range_to: 100
# Индикатор
        - meter:
            width: 200
            height: 200
            align: center
            scales:
              - indicators:
                  - line:
                      id: iaq_meter
                      width: 4
                      color: 0xFF0000
                      r_mod: -15
                      value: 0
                angle_range: 270
                rotation: 135
                range_from: 0
                range_to: 500
                ticks: 
                  count: 101
                  width: 0
                  length: 0
                  color: 0x000000
                  major:
                    stride: 10
                    width: 0
                    length: 0
                    color: 0x000000
                    label_gap: 8
                    
        - led:
           y: 65
           align: CENTER
           color: 808080
           width: 40
           height: 25         
        - label:
            id: iaq_index_text
            text: "--"
            text_color: color_violet
            align: CENTER
            y: 65
                  
        - spinner:
            width: 245
            height: 245
            align: center
            spin_time: 0s
            arc_length: 0deg
            arc_width: 3
            arc_color: 0x000000
            indicator:
              arc_width: 3
              arc_color: 0x000000
              

        - label:
            id: display_iaq_class
            text_color: color_white
            text_font: roboto36
            align: TOP_MID 
            y: 50
        - label:
            text: IAQ
            text_color: color_white
            text_font: weather36
            align: BOTTOM_MID
            y: -40
            
     #   - image:
      #      align: CENTER
      #      src: iaq
     #       y: 180
      #      bg_color: 0xFFFFFF
        #    bg_image_opa: 100% 
