substitutions:
  ceiling_light_multiple_outline:    "\U000F18DE"
  string_lights:                     "󱊺"
  television_ambient_light:          "󱍖"
  light_flood_down:                  "󱦇"
  alarm_light_on:                    "󰯪"
  countertop_outline:                "󱠝"
  television:                        "󰟴" #F07F4
  cctv:                              "\U000F07AE"
  coach_lamp:                        "\U000F1020"  
  door:                              "\U000F081A"

#-------------------------------------------
# FONT
#-------------------------------------------  
font:
  - file: 'font/materialdesignicons-webfont.ttf' # http://materialdesignicons.com/cdn/7.4.47/ 
    id: kitchen130
    size: 130
    bpp: 4
    glyphs: [
      $ceiling_light_multiple_outline # mdi-ceiling-light-multiple-outline
      ]   

  - file: 'font/materialdesignicons-webfont.ttf' # http://materialdesignicons.com/cdn/7.4.47/ 
    id: kitchen48
    size: 48
    bpp: 4
    glyphs: [
      $string_lights,
      $television_ambient_light,
      $alarm_light_on,
      $countertop_outline,
      $light_flood_down,
      $television,
      $cctv,                          
      $coach_lamp,                   
      $door                     
    ]      

#-------------------------------------------
# SCRIPT
#-------------------------------------------    
script:
  - id: time_update_kitchen
    then:
      - lvgl.label.update: 
          id: display_time_kitchen
          text: !lambda |-
            static char time_buf[17];
            auto now = id(sntp_time).now();            
            snprintf(time_buf, sizeof(time_buf), "%02d:%02d", now.hour, now.minute);
            return time_buf; 
      - lvgl.label.update:
          id: display_date_kitchen
          text: !lambda |-
            static char time_buf[17];
            auto now = id(sntp_time).now();            
            snprintf(time_buf, sizeof(time_buf), "%02d.%02d.%02d", now.day_of_month, now.month, now.year-2000);
            return time_buf; 
#-------------------------------------------
# TIME
#-------------------------------------------
time:
  - platform: sntp
    on_time_sync:
      - script.execute: time_update_kitchen
    on_time:
      - minutes: '*'
        seconds: 0
        then:
          - script.execute: time_update_kitchen
          
#-------------------------------------------
# Binary sensor
#-------------------------------------------
binary_sensor:
#-------------------------------------------
# Прожектор улица
#-------------------------------------------
  - platform: homeassistant
    name: bin_p_outdor
    entity_id: switch.wi_fi_smart_switch_switch_1
    publish_initial_state: true
    internal: true
    on_state:
      then:
        lvgl.widget.update:
          id: b_p_outdor
          state:
            checked: !lambda return x;
    on_press:
      lvgl.widget.update:
        id: w_p_outdor
        text_color: 0xFFFF00
    on_release:
      lvgl.widget.update:
        id: w_p_outdor
        text_color: 0xB6B6B6
#-------------------------------------------
# Кухня
#-------------------------------------------
  - platform: homeassistant
    name: bin_kitchen_n
    entity_id: light.kitchen_n
    publish_initial_state: true
    internal: true
    on_state:
      then:
        lvgl.widget.update:
          id: b_kitchen_n
          state:
            checked: !lambda return x;
    on_press:
      lvgl.widget.update:
        id: w_kitchen_n
        text_color: 0xFFFF00
    on_release:
      lvgl.widget.update:
        id: w_kitchen_n
        text_color: 0xB6B6B6

  - platform: homeassistant
    name: bin_kitchen_v
    entity_id: light.kitchen_v
    publish_initial_state: true
    internal: true
    on_state:
      then:
        lvgl.widget.update:
          id: b_kitchen_v
          state:
            checked: !lambda return x;
    on_press:
      lvgl.widget.update:
        id: w_kitchen_v
        text_color: 0xFFFF00
    on_release:
      lvgl.widget.update:
        id: w_kitchen_v
        text_color: 0xB6B6B6
#-------------------------------------------
# Кухня подсветка
#-------------------------------------------
  - platform: homeassistant
    name: bin_kitchen_lighting_0
    entity_id: light.kithcen_lighting_ch0
    publish_initial_state: true
    #internal: true
    on_state:
      then:
        lvgl.widget.update:
          id: b_kitchen_lighting_0
          state:
            checked: !lambda return x;
    on_press:
      lvgl.widget.update:
        id: w_kitchen_lighting_0
        text_color: 0xFFFF00
    on_release:
      lvgl.widget.update:
        id: w_kitchen_lighting_0
        text_color: 0xB6B6B6

  - platform: homeassistant
    name: bin_kitchen_lighting_1
    entity_id: light.kithcen_lighting_ch1
    publish_initial_state: true
    internal: true
    on_state:
      then:
        lvgl.widget.update:
          id: b_kitchen_lighting_1
          state:
            checked: !lambda return x;
    on_press:
      lvgl.widget.update:
        id: w_kitchen_lighting_1
        text_color: 0xFFFF00
    on_release:
      lvgl.widget.update:
        id: w_kitchen_lighting_1
        text_color: 0xB6B6B6

  - platform: homeassistant
    name: bin_kitchen_lighting_2
    entity_id: light.kithcen_lighting_ch2
    publish_initial_state: true
    internal: true
    on_state:
      then:
        lvgl.widget.update:
          id: b_kitchen_lighting_2
          state:
            checked: !lambda return x;
    on_press:
      lvgl.widget.update:
        id: w_kitchen_lighting_2
        text_color: 0xFFFF00
    on_release:
      lvgl.widget.update:
        id: w_kitchen_lighting_2
        text_color: 0xB6B6B6

  - platform: homeassistant
    name: bin_kitchen_lighting_3
    entity_id: light.kithcen_lighting_ch3
    publish_initial_state: true
    internal: true
    on_state:
      then:
        lvgl.widget.update:
          id: b_kitchen_lighting_3
          state:
            checked: !lambda return x;
    on_press:
      lvgl.widget.update:
        id: w_kitchen_lighting_3
        text_color: 0xFFFF00
    on_release:
      lvgl.widget.update:
        id: w_kitchen_lighting_3
        text_color: 0xB6B6B6
        
        
###############################################################
  - platform: homeassistant
    name: bin_vhod_light
    entity_id: light.vhod
    publish_initial_state: true
    internal: true
    on_state:
      then:
        lvgl.widget.update:
          id: b_vhod_light
          state:
            checked: !lambda return x;
    on_press:
      lvgl.widget.update:
        id: w_vhod_light
        text_color: 0xFFFF00
    on_release:
      lvgl.widget.update:
        id: w_vhod_light
        text_color: 0xB6B6B6
        
  - platform: homeassistant
    name: bin_vihod_light
    entity_id: light.vihod
    publish_initial_state: true
    internal: true
    on_state:
      then:
        lvgl.widget.update:
          id: b_vihod_light
          state:
            checked: !lambda return x;
    on_press:
      lvgl.widget.update:
        id: w_vihod_light
        text_color: 0xFFFF00
    on_release:
      lvgl.widget.update:
        id: w_vihod_light
        text_color: 0xB6B6B6
        
  - platform: homeassistant
    name: bin_cam
    entity_id: light.cam
    publish_initial_state: true
    internal: true
    on_state:
      then:
        lvgl.widget.update:
          id: b_cam
          state:
            checked: !lambda return x;
    on_press:
      lvgl.widget.update:
        id: w_cam
        text_color: 0xFFFF00
    on_release:
      lvgl.widget.update:
        id: w_cam
        text_color: 0xB6B6B6        


#-------------------------------------------
# LVGL
#-------------------------------------------        
lvgl:
  pages:
    - id: kitchen_page     
      width: 100%
      bg_color: 0x000000
      bg_opa: cover
      widgets:
        - image:
            align: CENTER
            src: $background_kitchen
        - button:
            x: 5
            y: 5
            width: 230
            height: 210
            checkable: true
            id: b_kitchen_v
            bg_opa: 35%
            widgets:
              - label:
                  text_font: kitchen130
                  align: center
                  text: $ceiling_light_multiple_outline
                  id: w_kitchen_v
              - label:
                  text_font: SEG36
                  id: display_time_kitchen
                  align: top_mid
                  text: "--:--"
                  long_mode: dot
              - label:
                  text_font: roboto36
                  align: bottom_mid
                  text: "Кухня верх"
                  long_mode: dot  
            on_click:
              - homeassistant.service:
                  service: light.toggle
                  data:
                    entity_id: light.kitchen_v
        - button:
            x: 245
            y: 5
            width: 230
            height: 210
            checkable: true
            id: b_kitchen_n
            bg_opa: 35%
            widgets:
              - label:
                  text_font: kitchen130
                  align: center
                  text: $ceiling_light_multiple_outline
                  id: w_kitchen_n
              - label:
                  text_font: SEG36
                  id: display_date_kitchen
                  align: top_mid
                  text: "--.--.--"
                  long_mode: dot
              - label:
                  text_font: roboto36
                  align: bottom_mid
                  text: "Кухня низ"
                  long_mode: dot    
            on_click:
              - homeassistant.service:
                  service: light.toggle
                  data:
                    entity_id: light.kitchen_n
        - button:
            x: 5
            y: 225
            checkable: true
            id: b_kitchen_lighting_0
            bg_opa: 35%
            widgets:
              - label:
                  text_font: kitchen48
                  align: center
                  text: $string_lights
                  id:  w_kitchen_lighting_0 
            on_click:
              - homeassistant.service:
                  service: light.toggle
                  data:
                    entity_id: light.kithcen_lighting_ch0
                  
        - button:
            x: 125
            y: 225
            checkable: true
            id: b_kitchen_lighting_1
            bg_opa: 35%
            widgets:
              - label:
                  text_font: kitchen48
                  align: center
                  text: $television_ambient_light
                  id: w_kitchen_lighting_1
            on_click:
              - homeassistant.service:
                  service: light.toggle
                  data:
                    entity_id: light.kithcen_lighting_ch1

        - button:
            x: 245
            y: 225
            checkable: true
            id: b_kitchen_lighting_2
            bg_opa: 35%
            widgets:
              - label:
                  text_font: kitchen48
                  align: center
                  text: $string_lights
                  id: w_kitchen_lighting_2
            on_click:
              - homeassistant.service:
                  service: light.toggle
                  data:
                    entity_id: light.kithcen_lighting_ch2

        - button:
            x: 365
            y: 225
            checkable: true
            id: b_kitchen_lighting_3
            bg_opa: 35%
            widgets:
              - label:
                  text_font: kitchen48
                  align: center
                  text: $television_ambient_light
                  id: w_kitchen_lighting_3
            on_click:
              - homeassistant.service:
                  service: light.toggle
                  data:
                    entity_id: light.kithcen_lighting_ch3

        - button:
            x: 5
            y: 340
            checkable: true
            id: b_vhod_light
            bg_opa: 35%
            widgets:
              - label:
                  text_font: kitchen48
                  align: center
                  text: $coach_lamp
                  id: w_vhod_light
            on_click:
              - homeassistant.service:
                  service: light.toggle
                  data:
                    entity_id: light.vhod

        - button:
            x: 125
            y: 340
            checkable: true
            id: b_vihod_light
            bg_opa: 35%
            widgets:
              - label:
                  text_font: kitchen48
                  align: center
                  text: $door
                  id: w_vihod_light
            on_click:
              - homeassistant.service:
                  service: light.toggle
                  data:
                    entity_id: light.vihod
        - button:
            x: 245
            y: 340
            checkable: true
            id: b_p_outdor
            bg_opa: 35%
            widgets:
              - label:
                  text_font: kitchen48
                  align: center
                  text: $light_flood_down
                  id:  w_p_outdor
            on_click:
              - homeassistant.service:
                  service: switch.toggle
                  data:
                    entity_id: switch.wi_fi_smart_switch_switch_1
        - button:
            x: 365
            y: 340
            checkable: true
            id: b_cam
            bg_opa: 35%
            widgets:
              - label:
                  text_font: kitchen48
                  align: center
                  text: $cctv
                  id: w_cam
            on_click:
              - homeassistant.service:
                  service: light.toggle
                  data:
                    entity_id: light.cam
                    