#-------------------------------------------
# IMAGE
#-------------------------------------------
image:
  - file: "picture/ragweed.png"
    id: ragweed_img
    resize: 60x60
    type: RGB565 
#-------------------------------------------
# SENSOR
#-------------------------------------------    
sensor:
  - platform: homeassistant
    id: ragweed_index
    entity_id: $sensor_ragweed
    on_value:
      then:
        - lvgl.label.update:
            id: ragweed_text
            text: 
              format: "%.0f"
              args: ["id(ragweed_index).state"]

        - lvgl.indicator.update:
            id: ragweed_meter
            value: !lambda |- 
              return x;
#-------------------------------------------
# LVGL
#-------------------------------------------
lvgl:
  pages:
# Вывод на экран 
    - id: ragweed_page
      #width: 100%
      bg_color: 0x000000
      #opa: cover
      scrollbar_mode: "OFF"
      scrollable: false
      widgets:
        # Зеленый
        - line:
            points:
              - 170, 170
              - -70, 410
            line_width: 200
            line_color: 0x00ff00
            line_rounded: false 
        # Желтый
        - line:
            points:
              - 90, 220
              - 120, 0
            line_width: 250
            line_color:  0xe7c12c
            line_rounded: false  
        # Оранжевый
        - line:
            points:
              - 170, 110
              - 480, -80
            line_width: 300
            line_color: 0xffa500
            line_rounded: false 
        # Красный
        - line:
            points:
              - 330, 295
              - 482, 0 #+5 -5
            line_width: 220
            line_color: 0xF50F34
            line_rounded: false 
         # Фиолетовый
        - line:
            points:
              - 360, 220
              - 390, 480
            line_color: 0xA63DC2 
            line_width: 240
            line_rounded: false
         # Белый
        - line:
            points:
              - 105, 585
              - 345, 345
            align: TOP_left
            line_width: 300
            line_color: 0xFFFFFF
            line_rounded: false 
# Шкала
        - meter:
            bg_opa: 0%
            opa: 100%
            #bg_color: color_blue
            shadow_color: color_blue
            shadow_spread: 2
            shadow_width: 25
            shadow_opa: 100%
            border_width: 15
            width: 300
            height: 300
            align: center
            scales:
              - ticks: 
                  count: 11
                  width: 2
                  length: 10
                  color: 0x000000
                  major:
                    stride: 2
                    width: 3
                    length: 20
                    color: 0x000000
                    label_gap: 10
                angle_range: 270
                rotation: 135
                range_from: 0
                range_to: 5
# Индикатор
        - meter:
            width: 200
            height: 200
            align: center
            scales:
              - indicators:
                  - line:
                      id: ragweed_meter
                      width: 4
                      color: 0xFF0000
                      r_mod: -15
                      value: 0
                angle_range: 270
                rotation: 135
                range_from: 0
                range_to: 5
                ticks: 
                  count: 6
                  width: 0
                  length: 0
                  color: 0x000000
                  major:
                    stride: 1
                    width: 0
                    length: 0
                    color: 0x000000
                    label_gap: 8
                    
        - led:
           y: 65
           align: CENTER
           color: 808080
           width: 40
           height: 25         
        - label:
            id: ragweed_text
            text: "-"
            text_color: color_violet
            align: CENTER
            y: 65
                  
        - spinner:
            width: 245
            height: 245
            align: center
            spin_time: 0s
            arc_length: 0deg
            arc_width: 3
            arc_color: 0x000000
            indicator:
              arc_width: 3
              arc_color: 0x000000
               
        - image:
            align: CENTER
            src: ragweed_img
            y: 180
            bg_color: 0xFFFFFF
            bg_image_opa: 100% 
