#############################################################################
#----Страничка с пыльцой амброзии----------------------------------------------
#############################################################################
# Add yaml and copy file esphome/packages/
#packages:
#
#  ragweed: !include 
#    file: packages/ragweed.yaml
#    vars:
#      sensor_ragweed: sensor.iaroslavskaia_ragweed_pollen_index
#-------------------------------------------
# IMAGE
#-------------------------------------------
image:
  - file: "picture/ragweed.png"
    id: ragweed_img
    resize: 60x60
    type: RGB565 
#-------------------------------------------
# SENSOR
#-------------------------------------------    
sensor:
  - platform: homeassistant
    id: ragweed_index
    entity_id: $sensor_ragweed
    filters:
      - filter_out: nan
    on_value:
      then:
        - lvgl.label.update:
            id: ragweed_text
            text: 
              format: " %.0f"
              args: ["id(ragweed_index).state"]

        - lvgl.indicator.update:
            id: ragweed_meter
            value: !lambda |- 
              return x;
        - lambda: |-
            uint8_t vgrass= (id(ragweed_index).state);
            switch (vgrass) {
              case 0 ... 2: return id(ragweed_class).publish_state("Низкое содержание");
              case 3: return id(ragweed_class).publish_state("Умеренное содержание");
              case 4: return id(ragweed_class).publish_state("Высокое содержание");
              case 5: return id(ragweed_class).publish_state("Очень высокое содержание");
              default: return id(ragweed_class).publish_state("n/a");
            }

################################################################              
        - lvgl.label.update:
            id: display_ragweed
            text: 
              format: "$flower_pollen %.0f"
              args: ["id(ragweed_index).state"]
            text_color: !lambda |-
              uint16_t vragweed = (id(ragweed_index).state);
              switch (vragweed) {
                case 0 ... 1: return lv_color_hex(0x00ff00);
                case 2: return lv_color_hex(0xe7c12c);
                case 3: return lv_color_hex(0xFFBB33);
                case 4: return lv_color_hex(0xff6600);
                case 5: return lv_color_hex(0xff0000);
                default: return lv_color_hex(0x333333);
              }  
################################################################ 
              
#-------------------------------------------
# TEXT SENSOR
#-------------------------------------------
text_sensor:             
  - platform: template
    id: ragweed_class
    on_value:
      then:
         - lvgl.label.update:
            id: display_ragweed_class
            text: !lambda |- 
              return x;            

#-------------------------------------------
# LVGL
#-------------------------------------------
lvgl:
  pages:
################################################################
# Добавляем на weather ragweed
    - id: !extend weather
      widgets:
        - button:
            y: 190
            x: 140
            align: LEFT_MID
            bg_opa: TRANSP
            shadow_opa: TRANSP
            width: 90
            height: 40
            widgets:  
              - label:
                  align: LEFT_MID
                  id: display_ragweed
                  text: --
                  text_font: weather24
                  text_color: 0x808080
            on_press:
              lvgl.page.show: ragweed_page
################################################################

# Вывод на экран 
    - id: ragweed_page
      #width: 100%
      bg_color: 0x000000
      #opa: cover
      scrollbar_mode: "OFF"
      scrollable: false
      widgets:
        # Зеленый
        - line:
            points:
              - 170, 170
              - -70, 410
            line_width: 200
            line_color: 0x00ff00
            line_rounded: false 
        # Желтый
        - line:
            points:
              - 90, 220
              - 120, 0
            line_width: 250
            line_color:  0xe7c12c
            line_rounded: false  
        # Оранжевый
        - line:
            points:
              - 170, 110
              - 480, -80
            line_width: 300
            line_color: 0xffa500
            line_rounded: false 
        # Красный
        - line:
            points:
              - 330, 295
              - 482, 0 #+5 -5
            line_width: 220
            line_color: 0xF50F34
            line_rounded: false 
         # Фиолетовый
        - line:
            points:
              - 360, 220
              - 390, 480
            line_color: 0xA63DC2 
            line_width: 240
            line_rounded: false
         # Белый
        - line:
            points:
              - 105, 585
              - 345, 345
            align: TOP_left
            line_width: 300
            line_color: 0xFFFFFF
            line_rounded: false
# Шкала
        - meter:
            bg_opa: 0%
            opa: 100%
            #bg_color: color_blue
            shadow_color: color_blue
            shadow_spread: 2
            shadow_width: 25
            shadow_opa: 100%
            border_width: 15
            width: 300
            height: 300
            align: center
            scales:
              - ticks: 
                  count: 11
                  width: 2
                  length: 10
                  color: 0x000000
                  major:
                    stride: 2
                    width: 3
                    length: 20
                    color: 0x000000
                    label_gap: 10
                angle_range: 270
                rotation: 135
                range_from: 0
                range_to: 5
# Индикатор
        - meter:
            width: 200
            height: 200
            align: center
            scales:
              - indicators:
                  - line:
                      id: ragweed_meter
                      width: 4
                      color: 0xFF0000
                      r_mod: -15
                      value: 0
                angle_range: 270
                rotation: 135
                range_from: 0
                range_to: 5
                ticks: 
                  count: 6
                  width: 0
                  length: 0
                  color: 0x000000
                  major:
                    stride: 1
                    width: 0
                    length: 0
                    color: 0x000000
                    label_gap: 8
                    
        - led:
           y: 65
           align: CENTER
           color: 808080
           width: 40
           height: 25         
        - label:
            id: ragweed_text
            text: "--"
            text_color: color_violet
            align: CENTER
            y: 65
                  
        - spinner:
            width: 245
            height: 245
            align: center
            spin_time: 0s
            arc_length: 0deg
            arc_width: 3
            arc_color: 0x000000
            indicator:
              arc_width: 3
              arc_color: 0x000000
        - label:
            id: display_ragweed_class
            text_color: color_white
            text_font: roboto36
            text: "нет"
            align: TOP_MID 
        - label:
            text_color: color_white
            text: пыльцы амброзии
            text_font: roboto36
            align: TOP_MID 
            y: 50
        - image:
            align: CENTER
            src: ragweed_img
            y: 180
            bg_color: 0xFFFFFF
            bg_image_opa: 100% 
