substitutions:
  ha:                 "\U0000e90b" # home assistant
  wifi_25:            "\U0000e90e" # wifi signal from 25% to 1% F090E
  wifi_50:            "\U0000e90f" # wifi signal from 50% to 25% F090F
  wifi_75:            "\U0000e910" # wifi signal from 75% to 50% F0910
  wifi_100:           "\U0000e911" # wifi signal from 100% to 75% or disable F0911
  lock_open:          "\U000F0340"
  lock_outline:       "\U000F0341"
  
#-------------------------------------------
# FONT
#-------------------------------------------
font:
  - file: "font/Icons.ttf"
    id: icons_24
    size: 24
    bpp: 4
    ignore_missing_glyphs: true
    glyphs: [
      $ha,
      $wifi_25,
      $wifi_50,
      $wifi_75,
      $wifi_100
      ]

  - file: 'font/materialdesignicons-webfont.ttf' # http://materialdesignicons.com/cdn/7.4.47/ 
    id: icons_lock
    size: 48
    bpp: 4
    glyphs: [
      $lock_open,
      $lock_outline
    ]    
esphome:
  on_boot:
    - lvgl.widget.hide: boot_screen
    
#-------------------------------------------
# API
#-------------------------------------------
api:
  on_client_connected:
    - if:
        condition:
          lambda: 'return (0 == client_info.find("Home Assistant "));'
        then:
          - lvgl.label.update: 
              id: ha_status
              text_color: color_blue
          
  on_client_disconnected:
    - if:
        condition:
          lambda: 'return (0 == client_info.find("Home Assistant "));'
        then:
          - lvgl.label.update: 
              id: ha_status
              text_color: color_dark_gray

#-------------------------------------------
# GLOBAL
#-------------------------------------------    
globals:
  - id: child_protection
    type: bool
    restore_value: true
    initial_value: "false" 
    
#-------------------------------------------
# SENSOR
#-------------------------------------------  
sensor:
  - id: !extend wifi_signal_percent
    on_value: 
      then:
        - lvgl.label.update:
            id: wifi_status
            text_color: !lambda |-
              uint8_t wifi_color = (id(wifi_signal_percent).state);
              switch (wifi_color) {
                case 0 ... 25: return lv_color_hex(0xFF0000);
                case 26 ... 50: return lv_color_hex(0xFF8000);
                case 51 ... 75: return lv_color_hex(0xFFFF00);
                case 76 ... 100: return lv_color_hex(0x00FF00);
                default: return lv_color_hex(0x333333);
              }
            text: !lambda |-
              uint8_t wifi_var = (id(wifi_signal_percent).state);
              switch (wifi_var) {
                case 0 ... 25: return std::string("${wifi_25}");
                case 26 ... 50: return std::string("${wifi_50}");
                case 51 ... 75: return std::string("${wifi_75}");
                case 76 ... 100: return std::string("${wifi_100}");
                default: return std::string("${wifi_100}");
              }

#-------------------------------------------   
# LVGL
#-------------------------------------------    
lvgl:
#############################################
  style_definitions:
    - id: style_line
      line_color: 0x0000FF
      line_width: 8
      line_rounded: true

    - id: header_footer
      bg_color: 0x2F8CD8
      bg_grad_color: 0x005782
      bg_grad_dir: VER
      bg_opa: cover
      border_width: 0
      radius: 0
      pad_all: 0
     # pad_row: 0
     # pad_column: 0
      border_color: 0x0077b3
      text_color: 0xFFFFFF
      width: 100%
      height: 30
#############################################
  theme:
    button:
      text_font: menu24
      scroll_on_focus: true
      radius: 25
      width: 110
      height: 100
      bg_color: 0x313131
      text_color: 0xB6B6B6
      checked:
        bg_color: 0xCC5E14
        text_color: 0xB6B6B6

    buttonmatrix:
      bg_opa: transp
      border_color: 0x0077b3
      border_width: 0
      text_color: 0xFFFFFF
      pad_all: 0
      items: # set all your btnmatrix buttins to use your custom defined styles and font
        bg_color: 0x2F8CD8
        bg_grad_color: 0x005782
        bg_grad_dir: VER
        bg_opa: cover
        border_color: 0x0077b3
        border_width: 1
        text_color: 0xFFFFFF
        text_font: menu24
        pressed:
          bg_color: 0x006699
          bg_grad_color: 0x00334d
        checked:
          bg_color: 0x1d5f96
          bg_grad_color: 0x03324A
          text_color: 0x005580

    slider:
      border_width: 1
      border_opa: 30%
      bg_color: 0x9c9c9c
      bg_opa: 15%
      indicator:
        bg_color: 0x333333
        bg_grad_color: 0x333333
        bg_opa: COVER
      knob:
        bg_color: 0x444444
        bg_grad_color: 0x444444
        bg_opa: COVER
        border_color: 0x444444
        border_width: 1
        text_color: 0xFFFFFF

#############################################
  top_layer:
      widgets:
        - obj:
            id: boot_screen
            x: 0
            y: 0
            width: 100%
            height: 100%
            bg_color: 0x000000
            bg_opa: COVER
            radius: 0
            pad_all: 0
            border_width: 0
            widgets:
              - image:
                  align: CENTER
                  src: $background_boot
                  y: -40
              - spinner:
                  align: CENTER
                  y: 95
                  height: 50
                  width: 50
                  spin_time: 1s
                  arc_length: 60deg
                  arc_width: 8
                  indicator:
                    arc_color: 0x18bcf2
                    arc_width: 8
            on_press:
              - lvgl.widget.hide: boot_screen

        - buttonmatrix:
            align: bottom_mid
            styles: header_footer
            pad_all: 0
            outline_width: 0
            id: top_layer
            items:
              styles: header_footer
            rows:
              - buttons:
                - id: page_prev
                  text: "\U000F0141"
                  on_press:
                    then:
                      lvgl.page.previous:
                - id: page_home
                  text: "\U000F06A1"
                  on_press:
                    then:
                      lvgl.page.show: $page_home
                - id: page_next
                  text: "\U000F0142"
                  on_press:
                    then:
                      lvgl.page.next:   

        # Child protection placeholder
        - button:
            id: child_protection_placeholder
            clickable: true
            hidden: true
            width: 480
            height: 480
            bg_opa: TRANSP
            border_opa: TRANSP
            shadow_opa: TRANSP
            
        # CHILD PROTECTION WIDGET
        - button:
           # x: -30
          #  y: 40
            width: 50
            height: 50
            bg_opa: TRANSP
            shadow_opa: TRANSP
            align: TOP_RIGHT
            widgets:
              - label:
                  id: child_protection_status
                  align: CENTER
                  text_font: icons_lock
                  text_color: color_gray
                  text: "${lock_open}"
            on_long_press:
              then:
                - if:
                    condition:
                      lambda: 'return id(child_protection) == false;'
                    then:
                      - lambda: |-
                          id(child_protection) = !id(child_protection); 
                      - lvgl.widget.show: child_protection_placeholder
                      - lvgl.widget.hide: top_layer
                      - lvgl.label.update:
                          id: child_protection_status
                          text: "${lock_outline}"
                          text_color: color_green
                    else:
                      - lambda: |-
                          id(child_protection) = !id(child_protection); 
                      - lvgl.widget.hide: child_protection_placeholder
                      - lvgl.widget.show: top_layer
                      - lvgl.label.update:
                          id: child_protection_status
                          text: "${lock_open}"
                          text_color: color_dark_gray
##################################
        - label:
            id: wifi_status
            align: BOTTOM_RIGHT #TOP_RIGHT
            x: -5
            y: -5
            text: "${wifi_100}"
            text_color: color_dark_gray
            text_font: icons_24
        - label:
            id: ha_status
            align: BOTTOM_RIGHT #TOP_RIGHT
            x: -30
            y: -5
            text: "${ha}"
            text_color: color_dark_gray
            text_font: icons_24

 # page_wrap: true