image: !include images2.yaml

#-------------------------------------------
#packages:
#  weather: !include 
#    file: packages/display/weather_anime.yaml
#    vars:
#      background_weather: back6
#      sensor_weather: weather.iaroslavskaia
#-------------------------------------------

substitutions:
  molecule_co2:       "\U000F07E4"
  gauge:              "\U000F029A"
  water_percent:      "\U000F058E"
  house_temp:         "\U000F0F55"
  temp:               "\U000F050F"
  checkbox_marked:    "\U000F0134"
  molecule:           "\U000F0BAC"
  
  sun_wireless:       "\U000F17FE"
  earth:              "\U000F01E7"
  flower_pollen:      "\U000F1885"
  grass:              "\U000F1510"
  tree_outline:       "\U000F0E69"
  windy:              "\U000F059D"

#-------------------------------------------
# FONT
#-------------------------------------------
font:
  - file: "gfonts://Roboto"
    id: weather36
    size: 36
    bpp: 4
    extras:
      - file: 'font/materialdesignicons-webfont.ttf' # http://materialdesignicons.com/cdn/7.4.47/ 
        glyphs: [
          $earth,
          $windy,
          $sun_wireless
          ]

  - file: "gfonts://Roboto"
    id: weather24
    size: 24
    bpp: 4
    extras:
      - file: 'font/materialdesignicons-webfont.ttf' # http://materialdesignicons.com/cdn/7.4.47/ 
        glyphs: [
          $molecule_co2,
          $checkbox_marked,
          $molecule,
          $gauge,
          $water_percent,
          $house_temp,
          $temp,
          $flower_pollen,
          $grass,
          $windy,
          $tree_outline
          ]
          
#-------------------------------------------
# TEXT SENSOR
#-------------------------------------------
text_sensor:
  # Sun horizon sensor from Home Assistant #
  - platform: homeassistant
    id: sun_state
    entity_id: sun.sun
    
  - platform: homeassistant
    id: weather_anime_state
    entity_id: $sensor_weather # Change the entity from your Home Assistant
    on_value: 
      then:
        - lambda: |-
            if (id(sun_state).state == "below_horizon" && (id(weather_anime_state).state == "cloudy" || id(weather_anime_state).state == "partlycloudy")) {
            lv_obj_clear_flag(id(weather_partlycloudy_moon), LV_OBJ_FLAG_HIDDEN);
            } else {
            lv_obj_add_flag(id(weather_partlycloudy_moon), LV_OBJ_FLAG_HIDDEN);
            }
            if (id(sun_state).state != "below_horizon" && id(weather_anime_state).state == "cloudy") {
            lv_obj_clear_flag(id(weather_cloudy), LV_OBJ_FLAG_HIDDEN);
            } else {
            lv_obj_add_flag(id(weather_cloudy), LV_OBJ_FLAG_HIDDEN);
            }
            if (id(sun_state).state != "below_horizon" && id(weather_anime_state).state == "partlycloudy") {
            lv_obj_clear_flag(id(weather_partlycloudy_sun), LV_OBJ_FLAG_HIDDEN);
            } else {
            lv_obj_add_flag(id(weather_partlycloudy_sun), LV_OBJ_FLAG_HIDDEN);
            }
            if ((id(sun_state).state != "below_horizon" && id(weather_anime_state).state == "sunny") || (id(sun_state).state != "below_horizon" && id(weather_anime_state).state == "clear-night")) {
            lv_obj_clear_flag(id(weather_sunny), LV_OBJ_FLAG_HIDDEN);
            } else {
            lv_obj_add_flag(id(weather_sunny), LV_OBJ_FLAG_HIDDEN);
            }
            if ((id(sun_state).state == "below_horizon" && id(weather_anime_state).state == "sunny") || (id(sun_state).state == "below_horizon" && id(weather_anime_state).state == "clear-night")) {
            lv_obj_clear_flag(id(weather_clear_night), LV_OBJ_FLAG_HIDDEN);
            } else {
            lv_obj_add_flag(id(weather_clear_night), LV_OBJ_FLAG_HIDDEN);
            }
            if (id(weather_anime_state).state == "rainy") {
            lv_obj_clear_flag(id(weather_rainy), LV_OBJ_FLAG_HIDDEN);
            } else {
            lv_obj_add_flag(id(weather_rainy), LV_OBJ_FLAG_HIDDEN);
            }
            if (id(weather_anime_state).state == "lightning-rainy") {
            lv_obj_clear_flag(id(weather_lightning_rainy), LV_OBJ_FLAG_HIDDEN);
            } else {
            lv_obj_add_flag(id(weather_lightning_rainy), LV_OBJ_FLAG_HIDDEN);
            }
            if (id(weather_anime_state).state == "lightning") {
            lv_obj_clear_flag(id(weather_lightning), LV_OBJ_FLAG_HIDDEN);
            } else {
            lv_obj_add_flag(id(weather_lightning), LV_OBJ_FLAG_HIDDEN);
            }
            if (id(weather_anime_state).state == "pouring") {
            lv_obj_clear_flag(id(weather_pouring), LV_OBJ_FLAG_HIDDEN);
            } else {
            lv_obj_add_flag(id(weather_pouring), LV_OBJ_FLAG_HIDDEN);
            }
            if (id(weather_anime_state).state == "snowy") {
            lv_obj_clear_flag(id(weather_snowy), LV_OBJ_FLAG_HIDDEN);
            } else {
            lv_obj_add_flag(id(weather_snowy), LV_OBJ_FLAG_HIDDEN);
            }
            if (id(weather_anime_state).state == "snowy-rainy") {
            lv_obj_clear_flag(id(weather_snowy_rainy), LV_OBJ_FLAG_HIDDEN);
            } else {
            lv_obj_add_flag(id(weather_snowy_rainy), LV_OBJ_FLAG_HIDDEN);
            }
            if (id(weather_anime_state).state == "fog") {
            lv_obj_clear_flag(id(weather_fog), LV_OBJ_FLAG_HIDDEN);
            } else {
            lv_obj_add_flag(id(weather_fog), LV_OBJ_FLAG_HIDDEN);
            }
            if (id(weather_anime_state).state == "hail") {
            lv_obj_clear_flag(id(weather_hail), LV_OBJ_FLAG_HIDDEN);
            } else {
            lv_obj_add_flag(id(weather_hail), LV_OBJ_FLAG_HIDDEN);
            }
            if (id(weather_anime_state).state == "windy") {
            lv_obj_clear_flag(id(weather_windy), LV_OBJ_FLAG_HIDDEN);
            } else {
            lv_obj_add_flag(id(weather_windy), LV_OBJ_FLAG_HIDDEN);
            }
            if (id(weather_anime_state).state == "windy-variant") {
            lv_obj_clear_flag(id(weather_windy_variant), LV_OBJ_FLAG_HIDDEN);
            } else {
            lv_obj_add_flag(id(weather_windy_variant), LV_OBJ_FLAG_HIDDEN);
            }

#-------------------------------------------
# LVGL
#-------------------------------------------
lvgl:
  pages:
    - id: weather
      scrollbar_mode: "OFF"
      scrollable: false
      bg_color: color_black
      widgets:
     #   - image:
     #       align: CENTER
     #       src: $background_weather

# WEATHER ICON  
        - animimg:
            id: weather_rainy
            hidden: true
            x: 120
            y: 20
            align: TOP_LEFT
            src: [ rainy0, rainy1, rainy2, rainy3, rainy4, rainy5, rainy6, rainy7, rainy8, rainy9, rainy10, rainy11]
            duration: 1200ms
        - animimg:
            id: weather_pouring
            hidden: true
            x: 120
            y: 20
            align: TOP_LEFT
            src: [ pouring0, pouring1, pouring2, pouring3, pouring4, pouring5, pouring6, pouring7, pouring8, pouring9, pouring10, pouring11 ]
            duration: 400ms
        - animimg:
            id: weather_lightning_rainy
            hidden: true
            x: 120
            y: 20
            align: TOP_LEFT
            src: [ lightning_rainy0, rainy1, lightning_rainy1, rainy3, rainy4, rainy5, rainy6, rainy7, rainy8, rainy9, rainy10, rainy11,
                    lightning_rainy2, rainy1, lightning_rainy3, rainy3, rainy4, rainy5, rainy6, rainy7, rainy8, rainy9, rainy10, rainy11
                  ]
            duration: 1500ms
        - animimg:
            id: weather_snowy_rainy
            hidden: true
            x: 120
            y: 20
            align: TOP_LEFT
            src: [ snowy_rainy0, snowy_rainy1, snowy_rainy2, snowy_rainy3, snowy_rainy4, snowy_rainy5, snowy_rainy6, snowy_rainy7, snowy_rainy8,
                    snowy_rainy9, snowy_rainy10, snowy_rainy11
                  ]
            duration: 1200ms
        - animimg:
            id: weather_snowy
            hidden: true
            x: 120
            y: 20
            align: TOP_LEFT
            src: [ snowy0, snowy1, snowy2, snowy3, snowy4, snowy5, snowy6, snowy7, snowy8, snowy9, snowy10, snowy11 ]
            duration: 1200ms
        - button:
            id: weather_sunny
            hidden: true
            pad_all: 0
            width: 100
            height: 100
            x: 120
            y: 20
            bg_opa: TRANSP
            shadow_opa: TRANSP
            widgets:
              - image:
                  src: sunny
        - button:
            id: weather_clear_night
            hidden: true
            pad_all: 0
            width: 100
            height: 100
            x: 120
            y: 20
            bg_opa: TRANSP
            shadow_opa: TRANSP
            widgets:
              - image:
                  src: clear_night
        - animimg:
            id: weather_hail
            hidden: true
            x: 120
            y: 20
            align: TOP_LEFT
            src: [ hail0, hail1, hail2, hail3, hail4, hail5, hail6, hail7, hail8, hail9, hail10, hail11 ]
            duration: 1200ms
        - animimg:
            id: weather_partlycloudy_sun
            hidden: true
            x: 120
            y: 20
            align: TOP_LEFT
            src: [ partlycloudy_sun0, partlycloudy_sun1, partlycloudy_sun2, partlycloudy_sun3, partlycloudy_sun4, partlycloudy_sun5, partlycloudy_sun6, 
                    partlycloudy_sun7, partlycloudy_sun6, partlycloudy_sun5, partlycloudy_sun4, partlycloudy_sun3, partlycloudy_sun2, partlycloudy_sun1 
                  ]
            duration: 2600ms
        - animimg:
            id: weather_partlycloudy_moon
            hidden: true
            x: 120
            y: 20
            align: TOP_LEFT
            src: [ partlycloudy_moon0, partlycloudy_moon1, partlycloudy_moon2, partlycloudy_moon3, partlycloudy_moon4, partlycloudy_moon5, partlycloudy_moon6,
                    partlycloudy_moon7, partlycloudy_moon6, partlycloudy_moon5, partlycloudy_moon4, partlycloudy_moon3, partlycloudy_moon2, partlycloudy_moon1 
                  ]
            duration: 2600ms
        - animimg:
            id: weather_windy
            hidden: true
            x: 120
            y: 20
            align: TOP_LEFT
            src: [ windy0, windy1, windy2, windy3, windy2, windy1 ]
            duration: 1000ms
        - animimg:
            id: weather_windy_variant
            hidden: true
            x: 120
            y: 20
            align: TOP_LEFT
            src: [ windy_variant0, windy_variant1, windy_variant2, windy_variant3, windy_variant2, windy_variant1 ]
            duration: 1000ms
        - animimg:
            id: weather_lightning
            hidden: true
            x: 120
            y: 20
            align: TOP_LEFT
            src: [ lightning0, lightning1, lightning1, lightning1, 
                    lightning0, lightning1, lightning1, lightning1, 
                    lightning1, lightning1, lightning1, lightning1, 
                    lightning2, lightning3, lightning3, lightning3, 
                    lightning2, lightning3, lightning3, lightning3, 
                    lightning3, lightning3, lightning3, lightning3, 
                    lightning3, lightning3, lightning3, lightning3, 
                    lightning3, lightning3, lightning3, lightning3
                  ]
            duration: 2000ms
        - animimg:
            id: weather_fog
            hidden: true
            x: 120
            y: 20
            align: TOP_LEFT
            src: [ fog0, fog1, fog2, fog3, fog4, fog5, fog6, fog7, fog8, fog9, fog10, fog11, fog12, fog11, fog10, fog9, fog8, fog7, fog6, fog5, fog4, fog3, fog2, fog1 ]
            duration: 5000ms
        - animimg:
            id: weather_cloudy
            hidden: true
            x: 120
            y: 20
            align: TOP_LEFT
            src: [ cloudy0, cloudy1, cloudy2, cloudy3, cloudy2, cloudy1 ]
            duration: 600ms