#-------------------------------------------
#packages:
#  weather: !include 
#    file: packages/display/weather.yaml # выбрать один из трех weather
#    vars:
#      background_weather: back6
#      sensor_weather: weather.iaroslavskaia
#-------------------------------------------
animation: !include images_gif.yaml
#image: !include images_andr.yaml


substitutions:
  molecule_co2:       "\U000F07E4"
  gauge:              "\U000F029A"
  water_percent:      "\U000F058E"
  house_temp:         "\U000F0F55"
  temp:               "\U000F050F"
  checkbox_marked:    "\U000F0134"
  molecule:           "\U000F0BAC"
  
  sun_wireless:       "\U000F17FE"
  earth:              "\U000F01E7"
  flower_pollen:      "\U000F1885"
  grass:              "\U000F1510"
  tree_outline:       "\U000F0E69"
  windy:              "\U000F059D"

#-------------------------------------------
# FONT
#-------------------------------------------
font:
  - file: "gfonts://Roboto"
    id: weather36
    size: 36
    bpp: 4
    extras:
      - file: 'font/materialdesignicons-webfont.ttf' # http://materialdesignicons.com/cdn/7.4.47/ 
        glyphs: [
          $earth,
          $windy,
          $sun_wireless
          ]

  - file: "gfonts://Roboto"
    id: weather24
    size: 24
    bpp: 4
    extras:
      - file: 'font/materialdesignicons-webfont.ttf' # http://materialdesignicons.com/cdn/7.4.47/ 
        glyphs: [
          $molecule_co2,
          $checkbox_marked,
          $molecule,
          $gauge,
          $water_percent,
          $house_temp,
          $temp,
          $flower_pollen,
          $grass,
          $windy,
          $tree_outline
          ]
          

interval:
  - interval: 500ms
    then:
      - if: 
          condition:
            lambda: return id(ha_weather_cond).state == "clear-night";
          then:
            - animation.next_frame: clear_night_icons
            - lvgl.image.update:
                id: disp_weather_icons
                src: clear_night_icons
                
      - if: 
          condition:
            lambda: return id(ha_weather_cond).state == "cloudy";
          then:
            - animation.next_frame: cloudy_icons
            - lvgl.image.update:
                id: disp_weather_icons
                src: cloudy_icons
                
      - if: 
          condition:
            lambda: return id(ha_weather_cond).state == "exceptional";
          then:
            - animation.next_frame: exceptional_icons
            - lvgl.image.update:
                id: disp_weather_icons
                src: exceptional_icons
      - if: 
          condition:
            lambda: return id(ha_weather_cond).state == "fog";
          then:
            - animation.next_frame: fog_icons
            - lvgl.image.update:
                id: disp_weather_icons
                src: fog_icons
       
      - if: 
          condition:
            lambda: return id(ha_weather_cond).state == "hail";
          then:
            - animation.next_frame: hail_icons
            - lvgl.image.update:
                id: disp_weather_icons
                src: hail_icons   
      - if: 
          condition:
            lambda: return id(ha_weather_cond).state == "lightning";
          then:
            - animation.next_frame: lightning_icons
            - lvgl.image.update:
                id: disp_weather_icons
                src: lightning_icons
                
      - if: 
          condition:
            lambda: return id(ha_weather_cond).state == "lightning-rainy";
          then:
            - animation.next_frame: lightning_rainy_icons
            - lvgl.image.update:
                id: disp_weather_icons
                src: lightning_rainy_icons        
                
      - if: 
          condition:
            lambda: return id(ha_weather_cond).state == "partlycloudy";
          then:
            - animation.next_frame: partlycloudy_icons
            - lvgl.image.update:
                id: disp_weather_icons
                src: partlycloudy_icons
                
      - if: 
          condition:
            lambda: return id(ha_weather_cond).state == "pouring";
          then:
            - animation.next_frame: pouring_icons
            - lvgl.image.update:
                id: disp_weather_icons
                src: pouring_icons

      - if: 
          condition:
            lambda: return id(ha_weather_cond).state == "rainy";
          then:
            - animation.next_frame: rainy_icons
            - lvgl.image.update:
                id: disp_weather_icons
                src: rainy_icons

      - if: 
          condition:
            lambda: return id(ha_weather_cond).state == "snowy";
          then:
            - animation.next_frame: snowy_icons
            - lvgl.image.update:
                id: disp_weather_icons
                src: snowy_icons
                
      - if: 
          condition:
            lambda: return id(ha_weather_cond).state == "snowy-rainy";
          then:
            - animation.next_frame: snowy_rainy_icons
            - lvgl.image.update:
                id: disp_weather_icons
                src: snowy_rainy_icons
                
      - if: 
          condition:
            lambda: return id(ha_weather_cond).state == "sunny";
          then:
            - animation.next_frame: sunny_icons
            - lvgl.image.update:
                id: disp_weather_icons
                src: sunny_icons 

      - if: 
          condition:
            lambda: return id(ha_weather_cond).state == "windy";
          then:
            - animation.next_frame: windy_icons
            - lvgl.image.update:
                id: disp_weather_icons
                src:  windy_icons
                
      - if: 
          condition:
            lambda: return id(ha_weather_cond).state == "windy-variant";
          then:
            - animation.next_frame: windy_variant_icons
            - lvgl.image.update:
                id: disp_weather_icons
                src:  windy_variant_icons

      - if: 
          condition:
            lambda: return id(ha_weather_cond).state == "unknown";
          then:
            - lvgl.image.update:
                id: disp_weather_icons
                src:  blank_icons
      - if: 
          condition:
            lambda: return id(ha_weather_cond).state == "unavailable";
          then:
            - lvgl.image.update:
                id: disp_weather_icons
                src:  blank_icons
    
#-------------------------------------------
# TEXT SENSOR
#-------------------------------------------
text_sensor:
  - platform: homeassistant
    id: ha_weather_cond
    entity_id: $sensor_weather

#-------------------------------------------
# LVGL
#-------------------------------------------
lvgl:
  pages:
    - id: weather
      scrollbar_mode: "OFF"
      scrollable: false
      widgets:
        - image:
            align: CENTER
            src: $background_weather
        - image:
            align: CENTER
            src: blank_icons
            id: disp_weather_icons
            y: -160
            x: -75