#-------------------------------------------
# WI-FI
#-------------------------------------------

api:
  #password: !secret api_pass
  encryption:
    key:  !secret api_key
    
ota:
  - platform: esphome
    password: !secret ota_pass
    
  
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
 # power_save_mode: none
 
#-------------------------------------------
# TEXT SENSOR
#-------------------------------------------
text_sensor:
  - platform: wifi_info
    ip_address:
      name: "IP Address"
      icon: mdi:ip
    ssid:
      name: "SSID"
      icon: mdi:access-point-network
    mac_address:
      name: "Mac"
      icon: mdi:lan
#-------------------------------------------
# SENSOR
#-------------------------------------------
sensor:
  - platform: wifi_signal
    name: "Wifi"
    update_interval: 60s  
    id: wifi_signal_db
    entity_category: "diagnostic"
    
  # WI-FI Signal
  - platform: wifi_signal
    id: wifi_signal_percent
    update_interval: 30s
    filters:
      - lambda: return min(max(2 * (x + 100.0), 0.0), 100.0);
    unit_of_measurement: "%"
   