#-------------------------------------------
# IMAGE
#-------------------------------------------
#image:
#  - file: "picture/wind.png"
 #   id: sun_wind
 #   resize: 60x60
 #   type: RGB565 
#-------------------------------------------
# SENSOR
#-------------------------------------------    
sensor:
  - platform: homeassistant
    id: wind_sped
    entity_id: $sensor_wind_speed
    on_value:
      then:
        - lvgl.label.update:
            id: wind_index_text
            text: 
              format: " %.0f"
              args: ["id(wind_sped).state"]

        - lvgl.indicator.update:
            id: wind_meter
            value: !lambda |- 
              return x;
        - lambda: |-
            uint8_t vwind= (id(wind_sped).state);
              switch (vwind) {
                case 0: return id(wind_class).publish_state("Штиль"); 
                case 1: return id(wind_class).publish_state("Тихий");
                case 2 ... 3: return id(wind_class).publish_state("Лёгкий");
                case 4 ... 5: return id(wind_class).publish_state("Слабый");
                case 6 ... 7: return id(wind_class).publish_state("Умеренный");
                case 8 ... 10: return id(wind_class).publish_state("Свежий");
                case 11 ... 13: return id(wind_class).publish_state("Сильный");
                case 14 ... 17: return id(wind_class).publish_state("Крепкий"); 
                case 18 ... 20: return id(wind_class).publish_state("Очень крепкий");
                case 21 ... 24: return id(wind_class).publish_state("Шторм");
                case 25 ... 28: return id(wind_class).publish_state("Сильный шторм");
                case 29 ... 32: return id(wind_class).publish_state("Жестокий шторм");
                case 33 ... 100: return id(wind_class).publish_state("Ураган");
                default: return id(wind_class).publish_state("n/a");
              }
    
#-------------------------------------------
# TEXT SENSOR
#-------------------------------------------
text_sensor:
  - platform: homeassistant
    id: wind_bearing
    entity_id: $sensor_wind_bearing
    filters:
      - to_upper
      - substitute:
        - "SW -> Юго-Западный" 
        - "SE -> Юго-Восточный" 
        - "NW -> Северо-Западный" 
        - "NE -> Северо-Восточный" 
        - "N -> Северный" 
        - "S -> Южный" 
        - "W -> Западный"
        - "E -> Восточный"  
    on_value:
      then:
         - lvgl.label.update:
            id: display_wind_bearing
            text: !lambda |- 
              return x;              

  - platform: template
    id: wind_class
    on_value:
      then:
         - lvgl.label.update:
            id: display_wind_class
            text: !lambda |- 
              return x; 
#-------------------------------------------
# LVGL
#-------------------------------------------
lvgl:
  pages:
# Вывод на экран 
    - id: wind_page
      #width: 100%
      bg_color: 0x000000
      #opa: cover
      scrollbar_mode: "OFF"
      scrollable: false
      widgets:
        # Зеленый
        - line:
            points:
              - 284, 304
              - -10, 500
              #- 170, 170
              #- -70, 410
            line_width: 150
            line_color: 0x00ff00
            line_rounded: false 
            
            
        # Желтый
        - line:
            points:
              - 220, 200
              - -30, 365
            line_width: 100
            line_color: 0xe7c12c
            line_rounded: false    
            
        # Оранжевый
        - line:
            points:
              - 220, 185
              - -30, 270
            line_width: 110
            line_color: 0xffa500
            line_rounded: false 

        # Красный
        - line:
            points:
              - 90, 220
              - 120, 0
             # - 240, 120
             # - 0, 120
            line_width: 250
            line_color:  0xF50F34
            line_rounded: false 
        # Фиолетовый
        - line:
            points:
              - 240, 240
              - 480, 0 
            line_width: 700
            line_color: 0x9412FD
            line_rounded: false 
         # Черный
        - line:
            points:
              - 105, 585
              - 345, 345
            align: TOP_left
            line_width: 300
            line_color: 0x000000
            line_rounded: false 
# Шкала
        - meter:
            bg_opa: 0%
            opa: 100%
            #bg_color: color_blue
            shadow_color: color_blue
            shadow_spread: 2
            shadow_width: 25
            shadow_opa: 100%
            border_width: 15
            width: 300
            height: 300
            align: center
            scales:
              - ticks: 
                  count: 101
                  width: 2
                  length: 10
                  color: 0x000000
                  major:
                    stride: 10
                    width: 3
                    length: 20
                    color: 0x000000
                    label_gap: 10
                angle_range: 270
                rotation: 135
                range_from: 0
                range_to: 100
# Индикатор
        - meter:
            width: 200
            height: 200
            align: center
            scales:
              - indicators:
                  - line:
                      id: wind_meter
                      width: 4
                      color: 0xFF0000
                      r_mod: -15
                      value: 0
                angle_range: 270
                rotation: 135
                range_from: 0
                range_to: 100
                ticks: 
                  count: 101
                  width: 0
                  length: 0
                  color: 0x000000
                  major:
                    stride: 10
                    width: 0
                    length: 0
                    color: 0x000000
                    label_gap: 8
                    
        - led:
           y: 65
           align: CENTER
           color: 808080
           width: 40
           height: 25         
        - label:
            id: wind_index_text
            text: "--"
            text_color: color_violet
            align: CENTER
            y: 65
                  
        - spinner:
            width: 245
            height: 245
            align: center
            spin_time: 0s
            arc_length: 0deg
            arc_width: 3
            arc_color: 0x000000
            indicator:
              arc_width: 3
              arc_color: 0x000000
              
        - label:
            id: display_wind_bearing
            text_color: color_white
            text_font: roboto36
            align: TOP_MID  
        - label:
            id: display_wind_class
            text_color: color_white
            text_font: roboto36
            align: TOP_MID 
            y: 50
        - label:
            text: $windy
            text_color: color_white
            text_font: weather36
            align: BOTTOM_MID
            y: -40
            
     #   - image:
      #      align: CENTER
      #      src: wind
     #       y: 180
      #      bg_color: 0xFFFFFF
        #    bg_image_opa: 100% 
